packages/engine/src/lib/handler/loop-executor.ts

Fixes OPS-1360.
When resuming a workflow with a loop, we need to validate whether we are resuming one iteration or a block outside the loop. This PR fixes the validation if a loop's actionName belongs to the path to be resumed or not.
The path is a string like these:
- 'step_1,0.step_3' -> resume a iteration
- 'step_10' -> resume a block

Fix resume payload path validation in loop executor

---

packages/openops/src/index.ts
packages/openops/src/lib/aws/aws-common-properties.ts
packages/openops/src/lib/dry-run-property.ts

Fixes OPS-1381
Dry run is now used in actions not related to aws, this is just a minimal backend improvement

Move dryRunCheckbox out of aws-common-properties

---

.github/workflows/ci.yml

Fixes OPS-1261.
Fixed the tagging of docker images in PR builds. It will tag the image with the proper git SHA, allowing deployments to work from PRs.
Also consolidated the two docker image builds, relying on the fact that fork PRs don't have access to the "ECR_REGION" variable. In fork PRs we're not publishing the images, only building them for validation.

Fix CI workflow triggers and conditions

---

packages/ui-components/src/components/flow-canvas/canvas-context.test.tsx
packages/ui-components/src/components/flow-canvas/canvas-context.tsx
packages/ui-components/src/components/flow-canvas/canvas-controls/panning-mode-toggle-control.tsx

Fixes OPS-1392.
The `isInGrabMode` logic in PanningModeToggleControl and FlowCanvas needs to be in sync.
Currently, the logic PanningModeToggleControl is correct but not not in FlowCanvas.

Fix panning mode selection for Shift key modifier

---

packages/react-ui/src/app/features/builder/block-properties/auto-properties-form.tsx

Fixes OPS-1419
Removed from Number:
Removed from text:
Removed from long text:
Removed from date:
Removed from file:
Kept for toggles and dropdowns:

Disable showing dynamic toggle for simple properties

---

packages/blocks/aws/src/lib/actions/cli/aws-cli-action.ts
packages/blocks/aws/test/cli/aws-cli-action.test.ts
packages/blocks/azure/src/lib/actions/azure-cli-action.ts
packages/blocks/azure/src/lib/azure-cli.ts
packages/blocks/azure/test/azure-cli-action.test.ts
packages/blocks/azure/test/azure-cli.test.ts
packages/openops/src/index.ts
packages/openops/src/lib/cloud-cli-common.ts
packages/openops/test/cloud-cli-common.test.ts

Fixes OPS-1436
Since we will be adding a third CLI block, I thought it made sense to extract some common logic, especially the error logging and json parsing.

Extract common logic in cli block

---

packages/react-ui/src/app/features/builder/index.tsx
packages/ui-components/src/components/flow-canvas/canvas-context.test.tsx
packages/ui-components/src/components/flow-canvas/canvas-context.tsx
packages/ui-components/src/components/flow-canvas/canvas-controls/canvas-controls.tsx
packages/ui-components/src/components/flow-canvas/flow-canvas.tsx
packages/ui-components/src/components/flow-template/template-canvas.tsx
packages/ui-components/src/stories/flow-canvas/flow-canvas.stories.tsx

Fixes OPS-1422, OPS-1409
Added a ReadOnlyCanvasContext for view-only and templates canvas. 
https://www.loom.com/share/713cc1f56bff4763bb6e44ef8636418e

Fix readonly canvas & templates canvas glitch

---

packages/react-ui/src/app/features/builder/index.tsx
packages/ui-components/src/components/flow-canvas/canvas-context.test.tsx
packages/ui-components/src/components/flow-canvas/canvas-context.tsx

Fixes OPS-1426
Selecting a single step will cancel any multi-selection. Conversely, selecting multiple steps will clear any previously selected single step.
https://www.loom.com/share/99b8058536a541ef8bd116043956ce89

Can switch between single and multi-select in canavs

---

.devcontainer/codespaces.sh

Part of OPS-1433
Small fix for codespaces. Otherwise we get back 401 because the oauth lambda can't reach the codespace.

Expose port 4200 for slack interactions

---

packages/ui-components/src/components/flow-template/template-canvas.tsx

Fixes OPS-1462.
This PR documents the TODO (ticket OPS-1460) and patches the regression in TemplateCanvas

Patch template canvas ClipboardContextProvider to unblock weekly release

---

packages/react-ui/src/styles.css

Fixes OPS-1494
Visual changes:
https://www.loom.com/share/a9186651d98e40d79d2620d4c924eb62
The selection still works as expected in other browsers (tested both Chrome and Firefox)
React flow issue:
https://github.com/xyflow/xyflow/issues/4806

Fix Safari selection glitch

---

packages/blocks/openops-tables/src/actions/delete-record-action.ts
packages/blocks/openops-tables/src/actions/update-record-action.ts
packages/blocks/openops-tables/test/actions/delete-record-action.test.ts
packages/blocks/openops-tables/test/actions/update-record-action.test.ts
packages/openops/src/lib/openops-tables/rows.ts
packages/openops/test/openops-tables/rows.test.ts

Fixes OPS-1377.
The date must be in the format 'YYYY-MM-DD' and can include the time if the table is set to do so.
In case of invalid format:

Add support for date comparisons when inserting in tables

---

packages/ui-components/src/tailwind.css

Fixes #325
This looks like a shadcn or radix issue, as I see it reported in multiple places. Somehow in some cases after opening a modal / popup it leaves `pointer-events:none` in the body element, thus making the page not interactive. We should leave `pointer-events: auto` on the body, then it will behave correctly. 
https://github.com/shadcn-ui/ui/issues/6988
https://github.com/shadcn-ui/ui/issues/5350

Fix shadcn / radix pointer events none on body element

---

packages/server/api/src/app/project/project-controller.ts

Fixes OPS-1336
Return 401 whe project is not the current from the users session. The FE will logout.
In the loom flag service returned 500, probably the server was not up and running properly yet.
https://www.loom.com/share/cb4f53472f0047f5b7395a63efd57752

Logout when project id is different than the one from the session

---

packages/blocks/snowflake/src/index.ts
packages/blocks/snowflake/src/lib/actions/run-query.ts
packages/blocks/snowflake/test/run-query.test.ts

Part of OPS-1482.
This brings AP almost 1:1, with minor adaptations. The most notable is:
Value from `sqlText` input is inlined just in time before executing the query. 
In AP codebase, the sqlText input is inlined by the framework

Add Run query Snowflake action

---

packages/blocks/snowflake/src/index.ts
packages/blocks/snowflake/src/lib/actions/run-multiple-queries.ts
packages/blocks/snowflake/test/run-multiple-queries.test.ts

Part of OPS-1482 
This brings AP almost 1:1, with minor adaptations. The most notable is:
Each `sqlText` value in `sqlTexts` input is inlined just in time before executing the query. In the AP codebase, the `sqlText` input is inlined by the framework.

Add Run multiple queries Snowflake action

---

packages/react-ui/src/app/features/builder/blocks-selector/index.tsx
packages/react-ui/src/app/features/builder/builder-header/builder-header-action-bar.tsx
packages/react-ui/src/app/features/builder/builder-hooks.ts
packages/react-ui/src/app/features/builder/flow-canvas/nodes/step-node.tsx
packages/react-ui/src/app/features/builder/flow-version-undo-redo/hooks/flow-version-undo-redo.ts
packages/react-ui/src/app/features/builder/flow-version-undo-redo/hooks/tests/flow-version-undo-redo.test.ts
packages/react-ui/src/app/features/builder/index.tsx

Fixes OPS-1320
- When we add or replace a trigger or a step, the step settings are always shown
- Undo / Redo closes step settings
Deployed to UX
https://www.loom.com/share/2d1ea79dc9ff4904965f3a31c701bcfb

Fix right sidebar state logic 

---

.gitignore
packages/blocks/google-cloud/src/lib/google-cloud-cli.ts
packages/blocks/google-cloud/test/google-cloud-cli.test.ts

Part of OPS-1483
this is prep work for the above mentioned ticket, in the new action, there will be a multiselect dropdown for "recommenders", over which we will loop over to run the cli command, we dont want to set the project each time so this way we avoid duplicate calling logic.

Add runCommands to google-cli file

---

.github/prlint.json

Add OPC and CI as issue prefixes to PRLint

---

packages/blocks/snowflake/src/lib/common/custom-auth.ts

Fixes OPS-1537.
The connection form modal looks similar to the GoogleCloud connection. The user sees the markdown and has to scroll down for the form fields.
Google:
Snowflake:

Add a connection markdown for Snowflake block

---

packages/blocks/snowflake/src/lib/actions/run-multiple-queries.ts
packages/blocks/snowflake/src/lib/actions/run-query.ts
packages/blocks/snowflake/src/lib/common/configure-connection.ts
packages/blocks/snowflake/src/lib/common/custom-auth.ts

Fixes OPS-1537.
Follows the solution Snowflake support suggested on [Discourse](https://snowflake.discourse.group/t/reducing-connection-timeout-for-incorrect-account-identifier-in-snowflake-node-js-sdk/15990/3).
Upon running the Snowflake query, the user will get the generic "Request to Snowflake failed." error message. With maxLoginRetries = 2(default), it will respond promptly. 
On my tests, using maxLoginRetries=2 responds in less than 5s every time.

Setup connection maxLoginRetries prop

---

packages/blocks/snowflake/src/lib/common/custom-auth.ts

Improve connection docs wording for Max Login Retries in relation to incorrect account identifier

---

packages/server/api/src/app/workers/redis/redis-consumer.ts
packages/server/worker/src/lib/engine/call-engine.ts

Fixes OPS-1554.
Additional notes:
- If the engine continues running after the response, we try to update the job later, but the job is no longer in the queue. We are ignoring the second update

Ignore update when job is null or undefined

---

packages/blocks/jira-cloud/src/lib/common/index.ts
packages/blocks/jira-cloud/test/common/index.test.ts

Add try catch in sendJiraRequest to not return the whole error object.

---

.github/workflows/ci.yml

The automatic commit of third party licenses by dependabot stopped working since we moved to "pull request" trigger. This PR fixes that.
Part of OPS-195.

Fix committing third party license changes for dependabot

---

deploy/docker-compose/docker-compose.yml
docker-compose.yml

Part of OPS-1464.
I deployed the private ECR image first [on UX](https://github.com/openops-cloud/devops/commit/58970bfc4082b8e6e03d5dc0c00a244005b2ee4f) before creating a public analytics release: performed a sanity check and inspected logs to make sure seed code logged the expected things/

Update analytics service image to the latest available

---

deploy/docker-compose/docker-compose.yml
docker-compose.yml

Fixes OPS-1601.
This PR prevents this error when attempting to install OpenOps release without sudo:
"Error response from daemon: image with reference public.ecr.aws/openops/openops-tables:0.1.10 was found but its platform (linux/amd64) does not match the specified platform (linux/arm64)"

Specify platform: linux/amd64for services using Openops built Docker images

---

packages/server/api/src/app/ai/chat/ai-chat.controller.ts
packages/shared/src/lib/ai/chat/index.ts

Part of OPS-1588.
- We are only allowing text messages in the history, we will not save other types of messages

Restrict chat messages to text type

---

packages/react-ui/src/app/features/builder/ai-chat/lib/chat-api.ts
packages/react-ui/src/app/features/builder/builder-hooks.ts

Fixes OPS-1635.
Given the same workflow, when a user deletes the step with the name ' step_X` and recreates it, a step created later will also have the name `step_X`.
It's better to delete the AI Chat conversation in case the new step with the same name uses the same block as the previously deleted step.

Delete AI Chat conversation when user deletes step

---

packages/ui-components/src/components/custom/markdown.tsx

Fixes OPS-1615
This was causing a flicker, right now it's better to have it without the Resize observer, and later this component will be changed to a code highlighter.

Remove resize observer on messages height logic

---

packages/react-ui/src/app/features/ai/ai-settings-form.tsx
packages/react-ui/src/app/features/ai/lib/ai-form-utils.ts

Fixes OPS-1651.
We need baseUrl to be a part of providerSettings technically, but we want to separate them for the users 

Move `baseUrl` to `providerSettings` on AI page 

---

packages/react-ui/setup-tests.ts
packages/react-ui/src/app/features/builder/builder-header/builder-header-action-bar.tsx
packages/react-ui/src/app/features/builder/builder-header/builder-header.tsx
packages/react-ui/src/app/features/builder/builder-header/builder-publish-button.tsx
packages/react-ui/src/app/features/builder/builder-hooks.ts
packages/react-ui/src/app/features/builder/builder-types.ts
packages/react-ui/src/app/features/builder/data-selector/index.tsx
packages/react-ui/src/app/features/builder/flow-canvas/flow-builder-canvas.tsx
packages/react-ui/src/app/features/builder/flow-canvas/widgets/incomplete-settings-widget.tsx
packages/react-ui/src/app/features/builder/flow-version-undo-redo/push-flow-version-to-version-history.ts
packages/react-ui/src/app/features/builder/flow-versions/flow-versions-card.tsx
packages/react-ui/src/app/features/builder/flow-versions/index.tsx
packages/react-ui/src/app/features/builder/index.tsx
packages/react-ui/src/app/features/builder/run-details/index.tsx
packages/react-ui/src/app/features/builder/run-list/flow-run-card.tsx
packages/react-ui/src/app/features/builder/run-list/index.tsx
packages/react-ui/src/app/features/builder/tests/update-flow-version.test.ts
packages/react-ui/src/app/features/builder/tree-view/tree-view-sidebar.tsx
packages/react-ui/src/app/features/builder/update-flow-version.ts
packages/react-ui/src/app/features/navigation/side-menu/flow/flow-side-menu-header.tsx

Extract builder types and add tests for update-flow-version

---

ai-prompts/mcp.txt

Fixes OPS-1779
After the fix:
```
how to I save on EC2 idle instances with OpenOps?
OpenOps can help you save on EC2 idle instances through automation and optimization. Here's how you can do it:
Identify Idle Instances: Create a workflow that uses AWS CloudWatch metrics to identify EC2 instances with low or no utilization.
Automate Shutdown/Start-up: Implement a workflow that automatically shuts down idle instances during non-business hours and starts them up when they are needed. This is particularly useful for instances used in development or testing environments.
Notifications: Set up a workflow that sends notifications when an instance has been idle for a certain period of time. This can prompt a manual review to determine if the instance is still needed.
Tagging: Use tagging to track …
```

Adjust docs prompt

---

packages/ui-components/src/components/resizable-area/resizable-area.tsx

Fixes OPS-1823.
I've [triggered](https://github.com/openops-cloud/devops/actions/runs/15146613974) a deployment on UX env, it can be used for a quick test.
Demo using UX env: https://www.loom.com/share/49050daf55be4772ae2bc89b0a3ed45b

Fix iframe interference during resize by disabling pointer events

---

deploy/docker-compose/docker-compose.yml
docker-compose.yml

Fixes OPS-1207, OPS-1844.
A version of the platform with openops-tables:0.2.2 has been deployed on the test env (https://github.com/openops-cloud/devops/actions/runs/15272517999), and I used the environment to test the tickets above.

Bump openops-tables version to latest public release

---

packages/blocks/store/src/lib/actions/common.ts
packages/blocks/store/src/lib/actions/store-add-to-list.ts
packages/blocks/store/src/lib/actions/store-append-action.ts
packages/blocks/store/src/lib/actions/store-get-action.ts
packages/blocks/store/src/lib/actions/store-put-action.ts
packages/blocks/store/src/lib/actions/store-remove-from-list.ts
packages/blocks/store/src/lib/actions/store-remove-value.ts

Fixes OPS-1845.
- When we test a block, the flowRunId changes each time the button is clicked. We use the flowRunId to build the key for the storage service when using the RUN scope.
- Add a static value if we are testing a block.

Fix get a value from Storage block when testing a step

---

packages/react-ui/src/app/features/builder/ai-chat/lib/step-settings-ai-chat-hook.ts

Fixes OPS-1876.
This only affects the CLI step chat; there is a different endpoint for the AI assistant chat, which has a similar URL, `POST /v1/ai/conversation/open` which is not related at all to the spamming errors from [Production alerts](https://app.logz.io/#/dashboard/explore?switchToAccountId=1161904&query=(field%3A(name%3Aenvironment)%2Cinvalid%3A!f%2CisDisabled%3A!f%2Cnegate%3A!f%2Ctype%3AIS_ONE_OF%2Cvalue%3A!(demo%2Cstaging%2Canodot%2Canodot-demo%2Clegit-security%2Cprod))%2C(field%3A(name%3Aevent.actionType)%2Cinvalid%3A!f%2CisDisabled%3A!f%2Cnegate%3A!t%2Ctype%3AEXIST)%2C(field%3A(aggregatable%3A!t%2Cname%3A'(level%3A%20error%20OR%20message%3A%20%22*error*%22)%20AND%20(NOT%20level%3A%20debug)%20AND%20(NOT%20%22BLOCK_NOT_FOUND%22)%20AND%20(NOT%20%22A%20promise%20was%20rejected%22 …

Retrieve CLI Step Chat history only when blockName and actionName are available for the selectedStep

---

packages/react-ui/src/app/features/builder/data-selector/index.tsx
packages/react-ui/src/app/features/builder/test-step/test-action-section.tsx
packages/react-ui/src/app/features/builder/test-step/test-trigger-section.tsx
packages/react-ui/src/app/features/builder/update-flow-version.ts
packages/server/api/test/helpers/mocks/index.ts
packages/server/api/test/integration/ce/flow-template/flow-template.controller.test.ts
packages/server/api/test/integration/ce/flows/consumer/flow-consume.test.ts
packages/server/api/test/integration/ce/flows/flow.test.ts
packages/shared/src/lib/flows/actions/action.ts
packages/shared/src/lib/flows/triggers/trigger.ts
packages/shared/test/flow/flow-helper.test.ts

This reverts commit 5fdf8b74aea4f912c8e538625c1928f82dab3215.
Fixes OPS-1698
Issue when creating templates:

Revert "Adjut types to make step ids mandatory (#555)"

---

packages/react-ui/src/app/features/connections/lib/connections-utils.ts

Fixes OPS-1915.
Since [PR 744](https://github.com/openops-cloud/openops/pull/744) `POST /api/v1/app-connections` accepts an optional `authProviderKey`.  The Patch endpoint also accepts it.
I tested these usecases:
- create new connection from /connections screen
- update existing connection from /connections screen
- create new connection from step settings connection picker
- update existing connection from  step settings connection picker (Reconnect)

Add authProviderKey to create/edit connection default values to include it in request payloads

---

packages/react-ui/src/app/features/builder/tests/update-flow-version.test.ts
packages/react-ui/src/app/features/builder/update-flow-version.ts

Fixes OPS-1926.
I also increased the test coverage for FlowOperationType.DELETE_ACTION.
```
PASS   react-ui  packages/react-ui/src/app/features/builder/tests/update-flow-version.test.ts
updateFlowVersion
....
deleteChatRequest
✓ should call deleteChatRequest when deleting selected step with block and action names (4 ms)
✓ should not call deleteChatRequest when deleting non-selected step (2 ms)
✓ should not call deleteChatRequest when step has no block name (3 ms)
✓ should not call deleteChatRequest when step has no action name (3 ms)
✓ should handle errors in deleteChatRequest gracefully (4 ms)
✓ should handle errors in aiChatApi.delete gracefully (4 ms)
```
https://github.com/user-attachments/assets/58de3b22-836d-4b51-89cd-0e95ea7cbd30

Skip chat deletion if step is missing blockName or actionName

---

packages/server/api/src/app/flags/dev-flags.service.ts

Part of OPS-1890
Enable so we can test on internal environments

Enable connections provider

---

.github/workflows/release.yml

Use files.openops.com for the release domain

---

nginx.standard.conf

Fixes CI-51.
It uses the same settings as the [`nginx.gateway`](https://github.com/openops-cloud/openops/commit/7f5f8ecdc87b4e31320c54d9b9010e6e31843143) configuration.
Demo on Openops test environment:
https://www.loom.com/share/ae81b67b4bb941fc81f232a0776b444a

Add AI Streaming-specific setting for nginx.standard config

---

packages/react-ui/src/app/features/builder/data-selector/data-selector-cache.ts
packages/react-ui/src/app/features/builder/test-step/test-action-section.tsx
packages/react-ui/src/app/features/builder/test-step/test-trigger-section.tsx

Fixes OPS-1957
Put data from WS directly in the cache, we don't need an extra HTTP call

Fix extra call when doing test step / trigger

---

packages/react-ui/src/app/features/builder/test-step/index.tsx
packages/react-ui/src/app/features/builder/test-step/step-test-output-hooks.ts
packages/react-ui/src/app/features/builder/tests/step-test-output-hooks.test.tsx

Fixes OPS-1994
Because the data is saved without updating the main settings form, every update the the step resulted in losing the sample data. We simply need to update the form and it will go through the same update process as the rest of the form updates.
https://github.com/openops-cloud/openops/blob/9d849da8a4a019f74ec3845ea04270ee2fe92a45/packages/react-ui/src/app/features/builder/step-settings/index.tsx#L204

Fix resetting sample data on step updates

---

packages/cli/src/lib/commands/create-block.ts

Exclude Verdaccio install for blocks generated with create-block CLI

---

packages/cli/src/lib/utils/block-templates.ts

It fixes linting errors related to the code formatting checks.
Part of OPS-1931.

Format generated block code with Prettier

---

ai-prompts/mcp-aws-cost-unavailable.txt

Scope:
- Prevent hallucinations on non-AWS-related questions or questions related to AWS cost anomalies.
- Give better guidelines for how to configure AWS Cost MCP.
Fixes OPS-2033.

Improve the `mcp-aws-cost-unavailable` system prompt

---

packages/cli/src/lib/commands/create-block.ts
packages/cli/src/lib/utils/block-generators.ts
packages/cli/src/lib/utils/block-templates.ts
packages/cli/src/lib/utils/block-validators.ts

Fixes OPS-1931.
Because create-block was getting too big with the additional boilerplate template code, I created new modules and moved some of the code there.

Add CLI prompts to add boilerplate code for Authentication and opinionated folder structure

---

packages/react-ui/src/app/features/ai/ai-assistant-conversation.tsx
packages/react-ui/src/app/features/builder/ai-chat/step-settings-ai-conversation.tsx
packages/ui-components/src/components/ai-chat-container/ai-assistant-chat-container.tsx
packages/ui-components/src/components/ai-chat-container/ai-chat-input.tsx
packages/ui-components/src/components/ai-chat-container/ai-scroll-helpers.ts
packages/ui-components/src/components/ai-chat-container/step-settings-ai-chat-container.tsx

Fixes OPS-1740.
https://www.loom.com/share/a4ec27b03b8e4a91ad6330322fb9ed4d?sid=29b0ad50-7e01-4a41-8277-4f01e18bc1a3

Block making AI chat calls for pending statuses

---

packages/react-ui/src/app/features/builder/data-selector/data-selector-cache.ts
packages/react-ui/src/app/features/builder/data-selector/tests/data-selector-cache.test.ts
packages/react-ui/src/app/features/builder/run-details/flow-step-input-output.tsx
packages/react-ui/src/app/features/builder/test-step/index.tsx
packages/react-ui/src/app/features/builder/test-step/test-action-section.tsx
packages/react-ui/src/app/features/builder/test-step/test-sample-data-viewer.tsx
packages/react-ui/src/app/features/builder/test-step/test-trigger-section.tsx

Fixes OPS-1943.
Not related bug: 
https://linear.app/openops/issue/OPS-2072/when-loading-test-data-for-the-first-time-its-not-saved
Deployed on UX

Replace `JsonViewer` with `TestStepDataViewer`

---

THIRD_PARTY_LICENSES.txt
package-lock.json
package.json
packages/react-ui/src/app/routes/cloud-connection/cloud-logout-page.tsx

Fixes OPS-1358.
The bug does not reproduce consistently, and I suspect it's a bug in the client(browser) state.
Yes, there is a redux store under the hood ( see [cloud-connection-page](https://github.com/openops-cloud/openops/blob/cezudas/OPS-1358/packages/react-ui/src/app/routes/cloud-connection/cloud-connection-page.tsx#L51))
```
app.store.subscribe(() => {
const { auth } = app.store.getState();
// ... you then use auth.isLoading, auth.isAuthenticated, etc.
});
```
I expect the problem to be solved by [updating @frontegg/js to the latest](https://github.com/openops-cloud/openops/pull/908#discussion_r2182407578), but we need to merge and deploy on `app.openops.com` to actually validate it.

Update @frontegg/js and use ensure cleanup operations after logout are completed

---

.github/workflows/release.yml

Part of OPS-2054.
I tested by creating a custom release from this branch `cezudas/OPS-2054` using version name `0.3.1-test-OPS-2054` 
You can see the appropriate `update-release-version` action on the docs repository has been triggered by the release workflow [here](https://github.com/openops-cloud/openops/actions/runs/16151330556).
Related PR on the docs repository [here](https://github.com/openops-cloud/docs/pull/91).

Open a PR to the docs repo when a new release is out

---

packages/blocks/linear/src/lib/common/props.ts

Fixes OPS-2129.
1. Previously all labels are displayed irrespective of the selected team.
2. Now labels are filtered with the selected team which resulted in removing duplicates. 
- Screenshots
- Loom video

Fix linear block displaying duplicate labels by filtering with selected team

---

packages/react-ui/src/app/features/builder/ai-chat/lib/step-settings-ai-chat-hook.ts
packages/react-ui/src/app/features/builder/builder-hooks.ts

Fixes OPS-2102
- we did an /open call every time we select a step (even though the step does not supportAI)
- when we had step settings chat opened, selecting a trigger would lead to a loading chat state
https://www.loom.com/share/e31ef92c2a20400b919f218025fa6db2

Fix /open calls and empty AI step setting chat when selecting a trigger

---

compose.yaml

Fixes CI-42.
To keep your docker volumes before this change, you'll need to rename them.
First shut down running containers if there are any:
```
docker rm -f $(docker ps -aq)
```
Then copy the volumes into their new names:
```
docker volume create --name openopsdev_openops_tables_data
docker run --rm -it -v "openops_openops_tables_data:/from" -v "openopsdev_openops_tables_data:/to" alpine ash -c 'cd /from ; cp -av . /to'
docker volume rm openops_openops_tables_data
docker volume create --name openopsdev_postgres_data
docker run --rm -it -v "openops_postgres_data:/from" -v "openopsdev_postgres_data:/to" alpine ash -c 'cd /from ; cp -av . /to'
docker volume rm openops_postgres_data
```

Add openopsdev as the app name of the local compose file

---

THIRD_PARTY_LICENSES.txt
package-lock.json
package.json
packages/react-ui/src/app/features/ai/lib/assistant-ui-chat-hook.ts
packages/react-ui/src/app/features/builder/ai-chat/step-settings-assistant-ui-chat.tsx
packages/react-ui/src/app/features/builder/assistant-ui/hooks/use-step-settings-assistant-chat.ts
packages/react-ui/src/app/features/builder/interactive-builder.tsx
packages/ui-components/src/components/ai-chat-container/index.ts
packages/ui-components/src/components/ai-chat-container/step-settings-assistant-ui-chat-container.tsx
packages/ui-components/src/components/assistant-ui/markdown-text/markdown-text.tsx

Fixes OPS-2114.
There is a [known styling mismatch](https://linear.app/openops/issue/OPS-2265/misalignment-between-assistant-ui-chat-container-vs-data-selector) between Data Selector and AssistantUiChatContainer. It is not in the scope of this PR.
It can be tested on the test env, [here's](https://github.com/openops-cloud/devops/actions/runs/16619153520) the deployment.

Implement AssistantUI based step settings chat with inject support

---

packages/server/shared/src/lib/system/system.ts

Fixes OPS-2305.
PR will not be merged before [OPS-2259](https://linear.app/openops/issue/OPS-2259/add-custom-tool-display-for-code-tool) and dependent tasks are completed.

Enable AssistantUI via flag on OSS and localdev environments

---

packages/ui-components/src/components/assistant-ui/generate-code-tool/generate-code-tool.tsx

Fixes OPS-2331.
Before: 
After:

Fix  `GenerateCodeTool` component empty state

---

packages/blocks/aws/src/lib/actions/cli/aws-cli-action.ts
packages/blocks/aws/test/cli/aws-cli-action.test.ts

Fixes OPS-2147.
- Blocked command
- Blocked command without aws prefix
- Screenshots
- Loom video

Block some AWS cli commands to prevent faulty configuration state

---

packages/blocks/openops-tables/src/actions/update-record-action.ts
packages/blocks/openops-tables/test/actions/update-record-action.test.ts

Add toggle to truncate numeric values when inserting in OpenOps Table

---

packages/blocks/aws/src/lib/actions/ec2/ec2-modify-instance-action.ts

Fixes OPS-2365.
https://www.loom.com/share/d8759e0eac214d8a895e931bf2455bd4?sid=40bf5d79-b242-454d-8ecd-7e4b4be1c47f

Fix handling of empty `attributeName` in EC2 modify instance action

---

packages/react-ui/src/app/features/builder/block-properties/builder-json-wrapper.tsx

Fixes OPS-2401.
After plain inserting we will see the linter error, but it's fine as most of the cases it will be inserted into existing string 
https://www.loom.com/share/4df838aada4b475d8b639da673ac0ae6?sid=177a8085-00f2-42fd-8414-da4f1796b1f2

Remove redundant quotes from inserted text in builder JSON wrapper

---

ai-prompts/code.txt

Fixes OPS-2328.
I've tried to put it under **Code Quality Requirements** as **Clean: Generate code without any comments or logging statements**. But LLM didn't always follow these instructions. So I put them under **FORBIDDEN**
After changes to the prompt
Before making changes to the prompt

Modify AI code prompt to not include comments and logging statements

---

packages/shared/src/lib/flows/actions/action.ts
packages/shared/src/lib/flows/flow-operations.ts
packages/shared/src/lib/flows/sample-data.ts
packages/shared/src/lib/flows/triggers/trigger.ts

Add more schema descriptions

---

packages/react-ui/src/app/features/builder/data-selector/data-selector-cache.ts
packages/react-ui/src/app/features/builder/data-selector/tests/data-selector-cache.test.ts
packages/react-ui/src/app/features/builder/test-step/step-test-output-hooks.ts
packages/react-ui/src/app/features/flows/lib/flows-api.ts

Fixes OPS-2327.
Before and after demo: https://www.loom.com/share/605947d6957d40b79cc0bfeabe6d0263

Fix race condition when previously empty step output data is not rendered after clicking Test Step quickly

---

packages/engine/src/lib/handler/block-executor.ts
packages/engine/src/lib/handler/context/flow-execution-context.ts
packages/engine/src/lib/handler/loop-executor.ts
packages/engine/src/lib/helper/error-handling.ts
packages/engine/test/handler/flow-with-response.test.ts
packages/server/api/src/app/workers/engine-controller.ts
packages/server/api/test/unit/engine/engine-controller.test.ts

Part of OPS-2497
- FlowRunStatus was being used to specify the reason for the final state of the context
- FlowRunStatus was never Stopped even when the reason was Stopped

Add VerdictReason enum to avoid confusion with run status

---

.github/workflows/stale.yml

Part of CI-70.
- Runs every Monday at 16:30 UTC
- PRs are considered stale after 30 days of inactivity
- Issues are considered stale after 60 days of inactivity
- After a PR/issue is staled, it is closed after a grace period of 5 days
- If an issue or a PR is updated after it is staled, it will not be closed and the counter resets
- Although the default operations (30) is enough, I increased it to 50 just to be future proof
If everything looks good and after test run, I will work on making changes to send a message to Slack channel.

Add workflow to automatically mark and close stale PRs and issues

---

packages/engine/src/lib/handler/block-executor.ts
packages/engine/src/lib/handler/flow-executor.ts
packages/engine/test/handler/flow-with-response.test.ts

Fixes OPS-2632.
- The Stop execution step was marking the run as finished even though it was included inside a loop.
- Now we are marking the execution as finished only when we are returning from the engine to the server.

Fix Stop execution block to not change the verdict to SUCCEEDED

---

packages/ui-components/src/components/assistant-ui/generate-code-tool/generate-code-tool.tsx
packages/ui-components/src/components/code-editor/code-editor.tsx

Fixes OPS-2686, a regression from [0.5.1]( https://github.com/openops-cloud/openops/commit/dc9b4d89e421bcd14a4963f932bc661b4ad34318#diff-ae40b566f4aa99a3a54d173869c7970724faae543401a6262c572a0046bdd273L259).

Fix "Inject code" not visible in the AI code assistant

---

packages/react-ui/src/app/features/builder/step-settings/branch-settings/branch-single-condition.tsx
packages/react-ui/src/app/features/builder/step-settings/split-settings/single-condition.tsx

Add `TooltipWrapper` to display operation details for condition selectors

---

packages/server/api/src/app/flows/trigger/hooks/enable-trigger-hook.ts
packages/server/api/src/app/workers/memory/memory-queue.ts
packages/server/api/src/app/workers/redis/redis-migration.ts
packages/server/api/src/app/workers/worker-controller.ts
packages/server/shared/src/lib/job/index.ts
packages/server/shared/src/lib/job/job-data.ts
packages/server/worker/src/lib/api/server-api.service.ts
packages/server/worker/src/lib/executors/repeating-job-executor.ts
packages/server/worker/src/lib/executors/webhook-job-executor.ts

Fixes OPS-2696.
- If the trigger is scheduled, we continue using the flowVersionId as correlationId because we don't want to have runs in parallel. We want the second want to be ignored.

Add trigger strategy for repeatable jobs

---

packages/engine/src/lib/handler/context/flow-execution-context.ts
packages/engine/src/lib/handler/flow-executor.ts
packages/engine/src/lib/operations.ts
packages/server/api/src/app/ai/chat/user-message-handler.ts
packages/server/worker/src/lib/executors/flow-job-executor.ts
packages/shared/src/lib/engine/engine-operation.ts

Fixes OPS-2669.
- Changed the first value from '-1' to '0'
- We continually add to the previous value. When a workflow has pauses/resumes, the duration will be the sum of all the time the Engine was executing.

Fix workflow duration

---

packages/react-ui/src/app/features/connections/components/create-edit-connection-dialog-content.tsx
packages/react-ui/src/app/features/connections/lib/connections-utils.ts
packages/react-ui/src/app/features/connections/lib/tests/connections-utils.test.ts
packages/shared/src/lib/common/application-error.ts

Fixes OPS-2742.
We have a few blocks which could send the error message as an object instead of a string. Example blocks include Jira, SMTP, Ternary. So this PR converts the error object to string if it is not already a string (in the frontend).

Fix error object parsing for invalid connection

---

packages/react-ui/src/app/features/home/flows-table/flows-table.tsx
packages/react-ui/src/app/features/home/runs-table/runs-table.tsx
packages/react-ui/src/app/routes/flows/index.tsx
packages/react-ui/src/app/routes/runs/index.tsx
packages/ui-components/src/ui/data-table.tsx

Fixes OPS-2662.
This could be a regression of https://github.com/openops-cloud/openops/pull/1242
Since we are wrapping each cell in a row with *Link*, adding event handler directly to the tooltip is not working all the time. So we now do not wrap the *Flow status toggle* with Link. This prevents the flow navigation on clicking the status toggle. 
I've added a new prop to DataTable component to control interactive columns that should not be wrapped with *Link*

Prevent flow navigation on clicking workflow status toggle

---

packages/react-ui/src/app/common/hooks/platform-hooks.ts
packages/react-ui/src/app/routes/settings/general/index.tsx

Fixes OPS-2668
This pr hides the notification on not official releases

Update versions to exclude pre-release versions from version checks
