packages/blocks/sftp/project.json
packages/blocks/sftp/src/index.ts

Fix error regarding SFTP block not found

---

deploy/docker-compose/docker-compose.yml
docker-compose.yml

Update tables service image to latest public release

---

packages/react-ui/src/app/features/builder/flow-canvas/nodes/big-button.tsx
packages/react-ui/src/app/features/builder/flow-canvas/nodes/step-node.tsx
packages/ui-components/src/lib/flow-canvas-utils.test.ts
packages/ui-components/src/lib/flow-canvas-utils.ts
packages/ui-components/src/lib/mockFlowVersion.ts

Fixes OPS-851.
`BIG_BUTTON`, `PLACEHOLDER`, `LOOP_PLACEHOLDER` and triggers are not selectable 
Before the fix: https://www.loom.com/share/2146f95271484d1f9c3718846be65272?sid=0a1017e7-47ed-4348-b671-2d2836095a8f
After the fix: https://www.loom.com/share/c6047defdccf4cd7aac6217db4948daf?sid=df77b91b-b0d8-4b2f-86e3-8dcbc9412f2f

Fix builder nodes selection

---

packages/blocks/openops-tables/src/actions/get-table-url-action.ts
packages/blocks/openops-tables/src/index.ts
packages/blocks/openops-tables/test/actions/get-table-url-action.test.ts
packages/blocks/openops-tables/test/index.test.ts

Add action to return the link to an OpenOps table

---

README.md

Add link to stargazers in the repo

---

THIRD_PARTY_LICENSES.txt
package-lock.json
package.json

Fixes OPS-1385.
Release notes suggests there is no breaking change between 
See all releases between 12.0.3 and 12.4.4 [here (page 1)](https://github.com/xyflow/xyflow/releases?expanded=true&page=2&q=react) and [here (page 2)](https://github.com/xyflow/xyflow/releases?expanded=true&page=1&q=react).
https://www.loom.com/share/36fd6a99aac4400cb3d2d1623d4f9f51?sid=6cff3d73-d6a9-4899-a434-e1e1631ebb87
Playground in Storybook is available [here](https://67d165c65ae89f986943666d-qdjsnsyril.chromatic.com/?path=/story/components-flowcanvas--default)

Update React flow library to latest

---

packages/react-ui/src/styles.css

Use default cursor for FlowCanvas selection mode

---

packages/react-ui/src/app/features/builder/flow-canvas/flow-drag-layer.tsx
packages/react-ui/src/app/features/builder/flow-canvas/nodes/step-node.tsx
packages/ui-components/src/components/flow-canvas/canvas-context.tsx

Fix selection then hover over node

---

packages/react-ui/src/app/features/builder/flow-canvas/flow-builder-canvas.tsx
packages/react-ui/src/app/features/builder/flow-canvas/flow-drag-layer.tsx
packages/react-ui/src/app/features/builder/flow-canvas/nodes/step-node.tsx
packages/ui-components/src/components/flow-canvas/canvas-context.tsx
packages/ui-components/src/lib/flow-canvas-utils.ts

Preserve selected state in react flow nodes

---

packages/openops/src/lib/openops-tables/tables.ts
packages/openops/test/openops-tables/tables.test.ts
packages/server/api/src/app/database/seeds/openops-delete-old-opportunities-table.ts
packages/server/api/src/app/database/seeds/openops-opportunities-table-seed.ts

Fix "Seed delete opportunities table" not setting the seed

---

packages/react-ui/src/app/features/builder/flow-canvas/flow-builder-canvas.tsx

Fix lint in react-ui

---

packages/blocks/azure/src/lib/actions/azure-advisor-action.ts

Small display name change for azure advisor

---

deploy/docker-compose/docker-compose.yml
docker-compose.yml

Update analytics service image to the latest available

---

deploy/docker-compose/docker-compose.yml

Add missing restart attribute to the redis container

---

docker-compose.yml

Part of OPS-1415.
Enables the import of bigger files to a table.

Increase shm_size in tables container

---

packages/ui-components/src/components/knowledge-base-card/knowledge-base-card.tsx

Open Knowledge base links in a new tab

---

packages/react-ui/src/app/features/builder/builder-header/builder-publish-button.tsx
packages/react-ui/src/app/features/builder/flow-versions/flow-versions-card.tsx
packages/react-ui/src/app/routes/flows/id/index.tsx

Fixes OPS-1435
​In React Router, the `setSearchParams` function updates the query string parameters in the URL. This function performs a "PUSH" operation by default, adding a new entry to the browser's history stack.

Fix browser back button in workflow builder page

---

packages/react-ui/public/locales/en/translation.json
packages/react-ui/src/app/features/builder/flow-canvas/context-menu/canvas-context-menu-content.tsx
packages/react-ui/src/app/features/builder/index.tsx
packages/server/api/src/app/flags/flag.service.ts

Fix copy with keyboard on disabled flag

---

packages/react-ui/src/app/features/builder/flow-canvas/context-menu/canvas-context-menu-content.tsx
packages/react-ui/src/app/features/builder/index.tsx
packages/server/api/src/app/flags/flag.service.ts
packages/ui-components/src/components/flow-canvas/canvas-context.tsx
packages/ui-components/src/components/flow-canvas/constants.ts

Fixes OPS-1410.
https://www.loom.com/share/349fd3a4b45c4895b5cfc3bd2f52a0bc

Consider left click single block selection for keyboard copy shortcut

---

packages/blocks/azure/src/lib/actions/azure-advisor-action.ts
packages/blocks/azure/src/lib/actions/azure-cli-action.ts
packages/blocks/azure/src/lib/common-properties.ts
packages/blocks/azure/test/azure-advisor-action.test.ts
packages/blocks/azure/test/azure-cli-action.test.ts
packages/blocks/azure/test/common-properties.test.ts
packages/blocks/azure/test/index.test.ts
packages/openops/src/lib/cloud-cli-common.ts
packages/openops/test/cloud-cli-common.test.ts

Part of OPS-1427
as gcp will also use the "useHostLogin" functionality I moved the property over to a common file.

Move useHostLogin to a common file

---

packages/react-ui/src/app/features/builder/flow-canvas/context-menu/canvas-context-menu-content.tsx
packages/react-ui/src/app/features/builder/flow-canvas/context-menu/canvas-context-menu.tsx
packages/react-ui/src/app/features/builder/flow-canvas/nodes/step-action-wrapper.tsx
packages/react-ui/src/app/features/builder/flow-canvas/nodes/step-node.tsx
packages/react-ui/src/app/features/builder/index.tsx
packages/react-ui/src/styles.css
packages/server/api/src/app/flags/flag.service.ts

Fixes OPS-1443
Deployed to UX.

Adapt step menu, canvas menu and selection styles

---

packages/ui-components/src/components/flow-canvas/canvas-context.tsx

Fixes OPS-1452.
Before the fix: 
https://www.loom.com/share/5167ffbcf0284b1bb032213aad73f6ec
After: 
https://www.loom.com/share/9dab3defed644b5f8944024bd333ef02

Fix copy handling after left mouse click selection

---

packages/openops/src/lib/cli-command-wrapper.ts
packages/openops/test/cli-command-wrapper.test.ts

Remove stderr check from cli wrapper

---

packages/react-ui/src/app/features/builder/index.tsx
packages/ui-components/src/components/flow-canvas/clipboard-context.tsx

Add feature flag to clipboard context

---

packages/react-ui/src/app/features/builder/flow-canvas/context-menu/canvas-context-menu.tsx

Fixes OPS-1459.
https://www.loom.com/share/abce45c5efe14f97b3680ebc5b4b0a56?sid=4899c948-842d-41b6-aec4-87d3df9f6113

Hide 3dot menu after successful copy or paste action

---

packages/react-ui/src/app/features/builder/hooks/use-paste.ts
packages/ui-components/src/components/flow-canvas/canvas-context.tsx
packages/ui-components/src/components/flow-canvas/copy-paste-toast.tsx
packages/ui-components/src/components/index.ts

Add paste action toast

---

packages/blocks/google-cloud/src/index.ts

Add gcp to the block name

---

packages/react-ui/src/app/features/home/components/discover-premium-tile.tsx
packages/ui-components/src/components/flow-canvas/ai-widget.tsx

Open external links in a new tab

---

packages/react-ui/src/app/features/builder/index.tsx
packages/ui-components/src/components/flow-canvas/ai-widget.tsx

Fix data selector

---

packages/ui-components/src/components/flow-canvas/flow-canvas.tsx

Fixes OPS-1466.
Demo:
https://www.loom.com/share/da2d27d5c82540f0acaa9236f20d1b69

Clear out pre-existing selection upon clicking anywhere in the canvas outside the selection

---

packages/ui-components/src/components/flow-canvas/copy-paste-toast.tsx

Shorten copy/paste toast duration down to 2s

---

packages/ui-components/src/components/flow-canvas/canvas-controls/panning-mode-toggle-control.tsx

Align select mode tooltip positioning with other canvas controls

---

packages/react-ui/src/app/features/builder/hooks/use-paste.ts

Fixes OPS-1458
https://www.loom.com/share/585ac342c0634ea0874b477000fe3047

Reposition canvas on paste

---

packages/react-ui/public/locales/en/translation.json
packages/react-ui/src/app/features/builder/flow-canvas/context-menu/canvas-context-menu-content.tsx
packages/react-ui/src/app/features/builder/flow-canvas/context-menu/canvas-context-menu.tsx
packages/react-ui/src/app/features/builder/flow-canvas/context-menu/utils.ts

Fixes OPS-1491.
https://www.loom.com/share/e6488453b1a6409495c627b3533ff3f0

Add protocol and hostname check to disable problematic "paste" context menu actions in insecure contexts

---

packages/blocks/google-cloud/src/lib/common-properties.ts

Rename project to default project

---

packages/server/api/src/app/aws/pricing-module.ts
packages/server/api/src/app/aws/pricing-service.ts
packages/server/api/test/integration/cloud/aws/pricing-service.test.ts

Improve error message in the 'Get Price from Price catalog' action

---

packages/react-ui/src/app/features/home/components/home-get-started.tsx
packages/ui-components/src/components/flow-template/sample-template-card.tsx
packages/ui-components/src/components/flow-template/template-card-text.tsx

Add GCP sample template to home page

---

docker-compose.yml

Fix Table port in docker-compose file

---

packages/ui-components/src/components/flow-canvas/canvas-context.tsx

Fix copy outside canvas

---

packages/ui-components/src/components/flow-canvas/canvas-context.test.tsx
packages/ui-components/src/components/flow-canvas/canvas-context.tsx
packages/ui-components/src/hooks/use-key-press.ts

Fix use key press

---

.github/workflows/ci.yml

Add quiet flag on CI tests

---

packages/blocks/math-helper/src/lib/actions/addition.ts
packages/blocks/math-helper/src/lib/actions/division.ts
packages/blocks/math-helper/src/lib/actions/modulo.ts
packages/blocks/math-helper/src/lib/actions/multiplication.ts
packages/blocks/math-helper/src/lib/actions/subtraction.ts
packages/blocks/math-helper/test/addition.test.ts
packages/blocks/math-helper/test/devision.test.ts
packages/blocks/math-helper/test/modulo.test.ts
packages/blocks/math-helper/test/multiplication.test.ts
packages/blocks/math-helper/test/subtraction.test.ts

Fix calculation precision errors in Math-helper block

---

packages/blocks/aws/test/arn/parse-arn-action.test.ts
packages/openops/src/lib/aws/arn-handler.ts
packages/openops/test/arn-handler.test.ts

Return the service and partition in parse-arn action

---

.devcontainer/Dockerfile

Install the clis in the codespaces container

---

THIRD_PARTY_LICENSES.txt
package-lock.json
package.json
packages/ui-components/src/components/dynamic-toggle/dynamic-toggle.tsx
packages/ui-components/src/components/index.ts
packages/ui-components/src/components/tooltip-wrapper.tsx
packages/ui-components/src/stories/dynamic-toggle/dynamic-toggle.stories.tsx
packages/ui-components/src/tailwind.css
packages/ui-components/src/ui/toggle-group.tsx
packages/ui-components/src/ui/toggle.tsx
packages/ui-components/src/ui/tooltip.tsx
packages/ui-components/tailwind.base.config.cjs

Add new dynamic toggle in UI components

---

packages/ui-components/src/components/custom/markdown.tsx
packages/ui-components/src/components/flow-canvas/canvas-context.tsx
packages/ui-components/src/index.ts
packages/ui-components/src/lib/clipboard-utils.ts

Fixes OPC-61.
I extracted `copyFallback` logic to ui components, so it can be reused there
https://www.loom.com/share/3252add2a87f429ea01c7f4b3944dca6?sid=308ae5ec-326f-49ce-a484-75d12d50687b

Add copy fallback to markdown component

---

packages/react-ui/src/app/common/components/json-viewer.tsx

Fixes OPS-1523.
https://www.loom.com/share/dd006df0a0eb4af684c3109b0e03ad48?sid=c4b32f6e-f442-41d2-973e-40a73a4435d6

Add copy fallback for step output

---

packages/react-ui/src/app/common/components/json-viewer.tsx
packages/ui-components/src/components/custom/markdown.tsx
packages/ui-components/src/components/flow-canvas/copy-paste-toast.tsx
packages/ui-components/src/lib/constants.ts

Extract toast duration to constant

---

packages/server/worker/src/lib/engine/call-engine.ts

Remove EXECUTE_PROPERTY from engine cache

---

packages/ui-components/src/stories/autocomplete-input.stories.tsx
packages/ui-components/src/ui/autocomplete-input.tsx

Add input with autocomplete component

---

packages/blocks/databricks/src/index.ts

Add databricks category

---

packages/react-ui/src/app/features/connections/components/create-edit-connection-dialog-content.tsx
packages/ui-components/src/components/custom/markdown.tsx

Hide markdown copy button in connection

---

packages/server/api/src/app/database/migrations/1745309649736-AddProviderSettingsAndConstraintForAiConfig.ts
packages/server/api/src/app/database/postgres-connection.ts

Add providerSettings column to AI_Config table

---

packages/server/api/src/app/ai/config/ai-config.controller.ts
packages/server/api/src/app/ai/config/ai-config.service.ts
packages/server/api/test/unit/ai/ai-config.service.test.ts

Add delete ai config endpoint

---

packages/server/api/src/app/ai/chat/ai-chat.controller.ts
packages/server/api/src/app/ai/chat/ai-chat.service.ts
packages/server/api/test/unit/ai/ai-chat.service.test.ts
packages/shared/src/lib/ai/chat/index.ts

Add delete chat history endpoint

---

packages/openops/src/lib/ai/providers.ts
packages/openops/test/ai/providers.test.ts
packages/shared/src/lib/ai/providers/index.ts

Fix unnecessary information in providers response

---

packages/server/api/src/app/ai/config/ai-config.service.ts
packages/server/api/test/unit/ai/ai-config.service.test.ts

Fix apiKey being removed from object

---

packages/react-ui/src/app/features/builder/block-properties/auto-form-field-wrapper.tsx
packages/react-ui/src/app/features/builder/builder-hooks.ts

Fix regression - BuilderStateContext is not always provided in AutoFormFieldWrapper

---

ai-prompts/aws.txt

Add Non-interactive Mode to AWS prompt

---

packages/react-ui/src/app/features/builder/block-properties/dictionary-property.tsx

Part of OPS-1578.
Previous impl didn't support dynamic value update from outside. But we need it for AI settings . Also added placeholders 
https://www.loom.com/share/8ff87531010d4a0dada22be1abb79ff5?sid=1acf81b7-b58e-4fc2-aad0-3c23fa1d012f

Update dictionary field behavior

---

packages/server/api/src/app/ai/config/ai-config.service.ts
packages/server/api/test/unit/ai/ai-config.service.test.ts

Deduplicate config based on id

---

packages/server/api/src/app/ai/chat/prompts.service.ts

Fix typo in block names

---

packages/ui-components/src/components/ai-chat-messages/ai-chat-messages.tsx
packages/ui-components/src/components/ai-chat-messages/index.ts
packages/ui-components/src/components/ai-chat-messages/types.ts
packages/ui-components/src/components/custom/markdown.tsx
packages/ui-components/src/components/index.ts
packages/ui-components/src/stories/ai-chat/ai-chat-container.stories.tsx
packages/ui-components/src/stories/ai-chat/ai-chat-messages.stories.tsx
packages/ui-components/src/stories/ai-chat/sample-messages.ts
packages/ui-components/src/stories/markdown.stories.tsx

Add AI chat messages in UI components

---

packages/react-ui/src/app/features/flows/components/import-flow-dialog/import-flow-dialog.tsx

Fixes OPC-85.
https://www.loom.com/share/34ee773b1f214f74980a1bae8fff33da?sid=d1323363-84f8-4a1c-9d7f-6e2a10284d17

Fix workflow notes import

---

packages/ui-components/src/components/ai-chat-container/ai-chat-container.tsx

Chatbox prompt textarea should be sticky at the bottom

---

packages/react-ui/src/app/features/builder/run-details/flow-step-details-card-item.tsx
packages/react-ui/src/app/features/builder/run-details/loop-iteration-input.tsx

Fixes OPS-1622.
https://www.loom.com/share/df09c572f75244b983517fa1024e5804?sid=5075e83a-6e59-47a3-87e1-adb6cfa86b45

Update loop iterations control

---

ai-prompts/aws.txt
ai-prompts/azure-cli.txt
packages/react-ui/src/app/features/builder/ai-chat/conversation.tsx

Integrate messages in React UI

---

ai-prompts/gcp-cli.txt

Add gcp cli prompt

---

packages/react-ui/public/locales/en/translation.json
packages/react-ui/src/app/routes/settings/ai/index.tsx

Update AI settings page title

---

packages/react-ui/src/app/common/components/project-settings-layout.tsx

Hide AI settings page link

---

packages/react-ui/public/locales/en/translation.json
packages/react-ui/src/app/features/ai/lib/ai-settings-api.ts
packages/react-ui/src/app/features/ai/lib/ai-settings-hooks.ts
packages/react-ui/src/app/features/builder/block-properties/auto-form-field-wrapper.tsx

Fixes OPS-1613.
https://www.loom.com/share/dddbeae5f7804ec39df2da8cb82cda37?sid=954baab8-91d5-459e-88c0-87310d8250fd

Add configure AI link

---

packages/server/api/src/app/ai/config/ai-config.controller.ts
packages/server/api/src/app/ai/config/ai-config.service.ts
packages/server/api/test/unit/ai/ai-config.service.test.ts

Replace upsert config with save config

---

packages/react-ui/public/locales/en/translation.json
packages/react-ui/src/app/features/ai/lib/ai-form-utils.ts

Fix ai settings save toast

---

packages/react-ui/src/app/features/builder/block-properties/auto-form-field-wrapper.tsx

Fixes OPS-1650
Chat closed:
Chat open:

Fix generate with AI color

---

packages/react-ui/src/app/features/builder/block-properties/auto-form-field-wrapper.tsx
packages/react-ui/src/app/features/builder/index.tsx
packages/react-ui/src/app/features/builder/interactive-builder.tsx
packages/server/api/src/app/flags/flag.service.ts
packages/server/shared/src/lib/system/system-prop.ts

Fixes OPS-1648
Use variable:
`OPS_SHOW_AI_SETTINGS=true`

Enable AI via env variable

---

packages/server/api/src/app/database/seeds/openops-knonw-cost-types-by-application-seed.ts
packages/server/api/src/app/openops-tables/template-tables/create-known-cost-types-by-application-table.ts
packages/server/api/src/app/openops-tables/template-tables/seed-tables-for-templates.ts
packages/server/api/src/main.ts

Add seed table logic for known cost types

---

packages/react-ui/src/app/features/ai/ai-settings-form.tsx
packages/react-ui/src/app/features/ai/lib/ai-form-utils.ts

Fixes OPS-1651.
We need it to align with BE

Rename baseUrl to baseURL on AI settings page

---

packages/server/api/src/app/ai/chat/ai-chat.controller.ts
packages/server/api/src/app/ai/config/ai-config.controller.ts
packages/server/api/src/app/ai/config/ai-config.service.ts
packages/server/api/test/unit/ai/ai-config.service.test.ts

Get decrypted api key to validate ai provider

---

packages/ui-components/src/components/custom/markdown.tsx
packages/ui-components/src/stories/markdown.stories.tsx

Fixes OPS-1615
As textarea was quite problematic for this usecase, I think it's better to use content editable div in this case.
Please check Chromatic

Improve messages style

---

packages/react-ui/src/app/features/ai/ai-settings-form.tsx
packages/react-ui/src/app/features/builder/block-properties/auto-properties-form.tsx
packages/react-ui/src/app/features/connections/components/basic-secret-connection-settings.tsx
packages/react-ui/src/app/features/connections/components/oauth2-connection-settings.tsx
packages/react-ui/src/app/features/connections/components/secret-text-connection-settings.tsx

Disable autofill on password fields

---

packages/react-ui/src/app/features/ai/ai-settings-form.tsx

Fixes OPS-1664
https://www.loom.com/share/e9d1b90c06584d78a2c8f86b1c711c46?sid=7f58f82e-bdd9-4c25-a9bd-3d84ec54018b

Disable form when ai config is not enabled

---

packages/react-ui/src/app/features/builder/run-details/loop-iteration-input.tsx

Fix loop iterations control for 0 iterations 

---

deploy/docker-compose/nginx.gateway.conf

Fix nginx preventing streaming of AI responses

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.md

Align the github issue templates and links

---

packages/react-ui/src/app/features/builder/builder-hooks.ts

Fixes OPC-65
Will add a second [PR](https://github.com/openops-cloud/openops/pull/542/files) where I add some tests (as doing this requires refactoring out the builder state and update flow version function)
https://www.loom.com/share/24dcd6151b3e416fb1d9373516862d11

Select duplicated step

---

packages/react-ui/src/app/features/builder/builder-hooks.ts

Fixes OPC-65
https://www.loom.com/share/1d048ca429734112a0e5590a26a3e191

Select dragged step

---

packages/react-ui/src/app/constants/sidebar.ts
packages/react-ui/src/app/features/builder/index.tsx

Fix midpanel sizing behavior

---

packages/engine/test/handler/test-helper.ts
packages/react-ui/src/app/features/builder/blocks-selector/index.tsx
packages/server/api/src/app/flows/flow-version/flow-version.service.ts
packages/server/api/test/integration/ce/flows/flow.test.ts
packages/shared/src/lib/flows/actions/action.ts
packages/shared/src/lib/flows/flow-helper.ts
packages/shared/src/lib/flows/triggers/trigger.ts
packages/shared/test/flow/flow-helper.test.ts

Fixes OPS-1691
Those are still optional until a migration is created.

Add step ids on ADD Action

---

.junie/guidelines.md

Create guidelines for Junie

---

deploy/docker-compose/docker-compose.yml
docker-compose.yml

Update tables image

---

packages/react-ui/src/app/features/builder/test-step/test-action-section.tsx
packages/react-ui/src/app/features/builder/test-step/test-trigger-section.tsx
packages/react-ui/src/app/features/builder/test-step/use-step-test-output.ts
packages/react-ui/src/app/features/flows/lib/flows-api.ts

Adjust FE code to fetch lastTestDate from test output endpoint

---

ai-prompts/snowflake.txt
packages/blocks/snowflake/src/lib/actions/run-query.ts
packages/server/api/src/app/ai/chat/prompts.service.ts

Add snowflake prompt and AI button

---

ai-prompts/aws-athena.txt
packages/blocks/aws-athena/src/lib/actions/query-athena-action.ts
packages/server/api/src/app/ai/chat/prompts.service.ts

Add AI button and prompt for aws athena

---

packages/react-ui/src/app/features/builder/ai-chat/conversation.tsx
packages/react-ui/src/app/features/builder/ai-chat/lib/chat-api.ts
packages/react-ui/src/app/features/builder/update-flow-version.ts
packages/server/api/src/app/ai/chat/ai-chat.controller.ts
packages/server/api/src/app/ai/chat/ai-chat.service.ts
packages/server/api/test/unit/ai/ai-chat.service.test.ts
packages/server/api/test/unit/ai/prompts.service.test.ts
packages/shared/src/lib/ai/chat/index.ts

Add action name to AI chat context

---

ai-prompts/aws-cli.txt
ai-prompts/azure-cli.txt
ai-prompts/gcp-cli.txt

Add strict to cli prompts

---

ai-prompts/aws-cli.txt
ai-prompts/azure-cli.txt
ai-prompts/gcp-cli.txt

Add explanation to placeholder in prompts

---

ai-prompts/mcp.txt
packages/server/api/src/app/ai/ai.module.ts
packages/server/api/src/app/ai/chat/ai-chat.service.ts
packages/server/api/src/app/ai/chat/ai-mcp-chat.controller.ts
packages/server/api/src/app/ai/chat/prompts.service.ts
packages/shared/src/lib/ai/chat/index.ts

Fixes OPS-1733
Open session endpoint: `/api/v1/ai/conversation/open`
Conversation endpoint: `/api/v1/ai/conversation`
Delete endpoint DELETE `/api/v1/ai/conversation/:id`
Just for context, we will split the work into multiple PRs (this one just adds the endpoints but not the MCP capability):
- new endpoints
- update baserow image
- Add MCP for mintlify
- Add MCP for baserow
- Add MCP analytics
- Update MCP conversation endpoint to support recursive tool call with streaming

Add new AI endpoints that will support tool calling

---

ai-prompts/gcp-big-query.txt
packages/blocks/google-cloud/src/lib/actions/execute-sql-query-action.ts
packages/blocks/google-cloud/test/execure-sql-query-action.test.ts
packages/server/api/src/app/ai/chat/prompts.service.ts
packages/server/api/test/unit/ai/prompts.service.test.ts

Add AI button and prompt for BigQuery

---

packages/blocks/anodot/src/index.ts
packages/blocks/anodot/src/lib/account-property.ts
packages/blocks/anodot/src/lib/anodot-auth-property.ts
packages/blocks/anodot/src/lib/api-filters/get-x-recommendation-property.ts
packages/blocks/anodot/src/lib/comments/add-comment-action.ts
packages/blocks/anodot/src/lib/comments/delete-comment-action.ts
packages/blocks/anodot/src/lib/comments/update-comment-action.ts
packages/blocks/anodot/src/lib/get-recommendations-action-custom.ts
packages/blocks/anodot/src/lib/get-recommendations-action-predefined.ts
packages/blocks/anodot/src/lib/update-user-status-action.ts
packages/blocks/anodot/test/api-filters/get-x-recommendation-property.test.ts
packages/blocks/anodot/test/comments/add-comment-action.test.ts
packages/blocks/anodot/test/comments/delete-comment-action.test.ts
packages/blocks/anodot/test/comments/update-comment-action.test.ts
packages/blocks/anodot/test/update-user-status-action.test.ts

Fixes OPS-1735
Changed only labels, so it would be backward-compatible.

Rename Anodot block to Umbrella

---

packages/ui-components/src/components/sidebar/menu-footer.tsx
packages/ui-components/src/stories/button.stories.tsx
packages/ui-components/src/stories/sidebar/sidebar.stories.tsx
packages/ui-components/src/ui/button.tsx
packages/ui-components/src/ui/user-avatar-menu.tsx

Part of OPS-1731
- Screenshots
- Loom video

Update menu footer

---

packages/react-ui/src/app/features/builder/ai-chat/conversation.tsx
packages/ui-components/src/components/ai-chat-messages/ai-chat-messages.tsx
packages/ui-components/src/components/custom/markdown.tsx
packages/ui-components/src/components/custom/types.ts
packages/ui-components/src/stories/ai-chat/ai-assistant-chat-container.stories.tsx
packages/ui-components/src/stories/ai-chat/ai-chat-messages.stories.tsx
packages/ui-components/src/stories/ai-chat/step-settings-ai-chat-container.stories.tsx
packages/ui-components/src/stories/markdown.stories.tsx

Part of OPS-1731
We need it for AI assistant. As there is no context for injection, but coping the code is still useful 

Add markdown multiline code variation without inject

---

packages/ui-components/src/components/ai-chat-container/no-ai-enabled-popover.tsx
packages/ui-components/src/stories/ai-chat/no-ai-enabled.stories.tsx

Add close button to no AI popover

---

packages/ui-components/src/components/ai-chat-container/ai-assistant-chat-container.tsx

Part of OPS-1731.
Just a service change 
No ui changes

Fix Ai assistant glitch

---

ai-prompts/mcp.txt

Update MCP prompt to answer only relevant questions

---

ai-prompts/mcp.txt

Adjust mcp prompt

---

README.md

Update supported cloud providers in readme

---

packages/ui-components/src/components/ai-chat-container/ai-assistant-chat-container.tsx

Data selector and CLI action Ai Chats are up to date already - AI Assistant chat also needs updated color and size for the close (X) icon.
I wanted to push a commit on the [existing PR](https://github.com/openops-cloud/openops/pull/594), it got merged in the meantime, so I opened a small PR for it.
Fixes OPS-1731.

Small toggle adjustments to match Figma design

---

packages/ui-components/src/components/ai-chat-container/ai-assistant-chat-container.tsx

Adjust the spacing in AI assistant

---

packages/server/api/src/app/ai/chat/ai-mcp-chat.controller.ts

Increase LLM recursion depth

---

Dockerfile

Use a commit hash for superset-mcp

---

Dockerfile
packages/server/api/src/app/ai/chat/ai-mcp-chat.controller.ts

Use local variable for commit hash for superset-mcp

---

ai-prompts/mcp.txt
packages/server/api/src/app/ai/chat/ai-mcp-chat.controller.ts
packages/server/api/src/app/ai/chat/prompts.service.ts

Fix extra MCP prompt loading

---

ai-prompts/mcp-analytics.txt

Make it clearer how to retreive the datasets

---

.devcontainer/Dockerfile

Install MCPs in the devcontainer

---

packages/server/api/src/app/ai/chat/ai-mcp-chat.controller.ts
packages/server/api/src/app/ai/chat/ai-message-id-generator.ts
packages/server/api/test/unit/ai/ai-message-id-generator.test.ts

Move generateMessageId to file

---

packages/blocks/microsoft-teams/src/lib/common/microsoft-teams-auth.ts

Update MS Teams block permissions

---

packages/react-ui/src/app/features/ai/ai-assistant-chat.tsx
packages/react-ui/src/app/features/builder/builder-header/workflow-overview/workflow-overview-content.tsx
packages/react-ui/src/app/store/app-store.ts
packages/ui-components/src/components/ai-chat-container/ai-assistant-chat-container.tsx
packages/ui-components/src/components/resizable-area/resizable-area.tsx
packages/ui-components/src/stories/ai-chat/ai-assistant-chat-container.stories.tsx
packages/ui-components/src/stories/resizable-area/resizable-area.stories.tsx

Fixes OPS-1797.
Demo
https://www.loom.com/share/09d8b65dc96848409b78ffba5d54e327
A deployment has been [triggered](https://github.com/openops-cloud/devops/actions/runs/15130442324) on UX environment, so it can be used for a quick test.

Make AI Chatbot resizable

---

packages/react-ui/src/app/features/builder/step-settings/branch-settings/branch-single-condition.tsx
packages/react-ui/src/app/features/builder/step-settings/split-settings/single-condition.tsx

Fixes OPS-1816
https://www.loom.com/share/7063c5a4af424a50bcce341280fe6f89

Fix branch condition second value initialization

---

packages/ui-components/src/components/resizable-area/resizable-area.tsx

Fixes OPS-1822.
Demo before and after https://www.loom.com/share/6e8bba4a43fc4868a3667693e3e03c12
A deployment on UX has been [triggered](https://github.com/openops-cloud/devops/actions/runs/15137877003), UX env can be used for a quick test.

Do not resize AiChat box for transient maxHeight negative values

---

packages/openops/src/lib/ai/providers.ts
packages/openops/test/ai/providers.test.ts
packages/server/api/src/app/ai/config/ai-config.service.ts

Fixes OPS-1819
Their docs are not explicit if they collect any telemetry or not, so better to just disable it explicitly.

Disable AI SDK telemetry

---

packages/server/api/src/app/ai/chat/ai-mcp-chat.controller.ts

Fix inclusion of prompt for tables mcp tools

---

packages/server/api/src/app/flows/flow.module.ts
packages/server/api/src/app/telemetry/event-models/step.ts
packages/server/api/src/app/telemetry/event-models/workflow.ts
packages/server/api/src/app/telemetry/telemetry-event.ts

Add telemetry events for step and workflow failure

---

packages/react-ui/src/app/features/navigation/side-menu/dashboard/dashboard-side-menu.tsx
packages/react-ui/src/app/features/navigation/side-menu/flow/flow-side-menu.tsx
packages/react-ui/src/app/features/navigation/side-menu/side-menu-footer.tsx
packages/ui-components/src/components/sidebar/side-menu.tsx
packages/ui-components/src/stories/sidebar/sidebar.stories.tsx

Fix sidebar footer

---

packages/react-ui/src/app/features/ai/ai-assistant-chat.tsx
packages/react-ui/src/app/features/builder/index.tsx
packages/ui-components/src/components/ai-chat-container/ai-assistant-chat-container.tsx

Fixes OPS-1827.
Demo: https://www.loom.com/share/da40c2dadc6b405682555611433faaa5

Increase maximum height for AIChat resize and expanded state

---

packages/server/api/src/app/flows/trigger-events/trigger-event.service.ts

Fix trigger results not being added to test step output

---

.github/workflows/ci.yml
.github/workflows/release.yml

Add installation instructions for a release. Also rename Editor to App.
Fixes CI-46.

Add a release installation note to the release action

---

ai-prompts/mcp-tables.txt

Update tables prompt

---

packages/blocks/microsoft-teams/src/lib/common/microsoft-teams-auth.ts

Fixes OPS-1821.
Approved by Marco

Add MS Teams connection warning

---

packages/blocks/microsoft-teams/src/lib/actions/request-action-message.ts

Update MS Teams button public url

---

packages/react-ui/src/app/features/builder/builder-hooks.ts

Fixes OPS-1730.
https://www.loom.com/share/8433eb8fe5764d689516e50a6f860e4a?sid=2c448c96-3926-4c72-a617-2559e689f107

Open data selector only when clicking on minimized version

---

.github/workflows/ci.yml

Push single arch image

---

packages/blocks/microsoft-teams/src/lib/common/microsoft-teams-auth.ts

Fixes OPS-1847.
Added new permission to allow connection to refresh the token
https://learn.microsoft.com/en-us/entra/identity-platform/scopes-oidc
It doesn't require MS Teams admin approval

Update MS Teams auth permissions to allow token refresh

---

packages/react-ui/src/app/features/ai/ai-assistant-chat.tsx
packages/ui-components/src/components/ai-chat-messages/ai-chat-messages.tsx
packages/ui-components/src/components/custom/markdown.tsx

Update chatbot default width and font size

---

deploy/docker-compose/docker-compose.yml
docker-compose.yml
packages/react-ui/public/locales/en/translation.json
packages/react-ui/src/app/constants/menu-links.ts
packages/react-ui/src/app/features/navigation/lib/analytics-links-hook.tsx
packages/react-ui/src/app/features/navigation/side-menu/dashboard/dashboard-side-menu.tsx
packages/ui-components/src/components/sidebar/menu-navigation-item.tsx
packages/ui-components/src/components/sidebar/side-menu-navigation.tsx
packages/ui-components/src/components/sidebar/types.ts
packages/ui-components/src/icons/index.ts
packages/ui-components/src/icons/table-2-with-gear.tsx

Fixes OPS-1854.
It's on UX https://ux.internal.openops.com/analytics

Update analytics empty page and side menu

---

packages/react-ui/src/app/features/builder/flow-canvas/context-menu/canvas-context-menu.tsx
packages/react-ui/src/app/features/builder/test-step/step-test-output-hooks.ts
packages/react-ui/src/app/features/flows/lib/flows-api.ts
packages/shared/src/lib/flows/flow-helper.ts
packages/shared/src/lib/flows/flow-operations.ts
packages/shared/test/flow/flow-helper.test.ts

Fix duplicate action ids creation

---

packages/blocks/common/src/lib/helpers/index.ts
packages/blocks/github/src/index.ts
packages/blocks/github/test/index.test.ts

Add custom API action to GitHub block

---

packages/server/api/src/app/app.ts

Allow for untagged endpoints to be added to schema

---

packages/server/api/src/app/ai/chat/ai-chat.service.ts
packages/server/api/test/unit/ai/ai-chat.service.test.ts

Part of OPS-1787.
- This is not currently in use; it will be utilised in the PR with the summary of the chat history.

Add chat history context to ai-service

---

packages/react-ui/src/app/common/components/json-viewer.tsx

Fixes OPS-1895.
By default all fields are collapsed. Strings are truncated:

Fix large test output displaying

---

packages/react-ui/src/app/features/templates/lib/templates-hooks.ts
packages/react-ui/src/app/features/templates/lib/tests/templates-hooks.test.ts
packages/ui-components/src/components/flow-template/flow-template-filter-sidebar.tsx
packages/ui-components/src/components/flow-template/template-utils.ts
packages/ui-components/src/components/flow-template/tests/template-utils.test.ts

Fix template service filter

---

packages/engine/src/api-handler.ts
packages/server/api/src/app/ai/chat/ai-chat.controller.ts
packages/server/api/src/app/ai/chat/ai-mcp-chat.controller.ts
packages/server/api/src/app/ai/config/ai-config.controller.ts
packages/server/api/src/app/ai/providers/ai-providers.controller.ts
packages/server/api/src/app/app-connection/app-connection-worker-controller.ts
packages/server/api/src/app/app-connection/app-connection.controller.ts
packages/server/api/src/app/authentication/authentication.controller.ts
packages/server/api/src/app/blocks/base-block-module.ts
packages/server/api/src/app/file/file.controller.ts
packages/server/api/src/app/flags/flag.module.ts
packages/server/api/src/app/flow-template/cloud-template.controller.ts
packages/server/api/src/app/flow-template/flow-template.controller.ts
packages/server/api/src/app/flows/flow-run/flow-run-controller.ts
packages/server/api/src/app/flows/flow/flow-version.controller.ts
packages/server/api/src/app/flows/flow/flow.controller.ts
packages/server/api/src/app/flows/flow/form/form.controller.ts
packages/server/api/src/app/flows/folder/folder.module.ts
packages/server/api/src/app/flows/test-trigger/test-trigger-controller.ts
packages/server/api/src/app/organization/organization.controller.ts
packages/server/api/src/app/store-entry/store-entry.controller.ts
packages/server/api/src/app/webhooks/webhook-controller.ts
packages/server/api/src/app/webhooks/webhook-simulation/webhook-simulation-controller.ts
packages/server/api/src/app/workers/engine-controller.ts
packages/server/api/src/app/workers/machine/machine-controller.ts
packages/server/api/src/app/workers/worker-controller.ts

Add more descriptions to endpoints

---

packages/react-ui/src/app/features/builder/test-step/step-test-output-hooks.ts
packages/react-ui/src/app/features/builder/tests/step-test-output-hooks.test.tsx
packages/shared/src/lib/flows/sample-data.ts

Implement new hook for saving sample data for selected step

---

packages/react-ui/src/app/features/connections/components/connection-table.tsx
packages/react-ui/src/app/features/connections/components/new-connection-type-dialog.tsx

Use provider icons in connection screen

---

packages/ui-components/src/components/json-viewer/header-buttons.tsx
packages/ui-components/src/components/json-viewer/json-viewer-hook.ts
packages/ui-components/src/components/json-viewer/json-viewer.tsx

Update JsonViewer buttons behavior 

---

packages/blocks/archera/src/index.ts
packages/blocks/archera/src/lib/actions/apply-plan.ts
packages/blocks/archera/src/lib/actions/get-commitment-inventory.ts
packages/blocks/archera/src/lib/actions/get-commitment-plan.ts
packages/blocks/archera/src/lib/actions/get-default-plans.ts
packages/blocks/archera/src/lib/actions/get-metrics.ts

Fixes [OPS-1930](https://linear.app/openops/issue/OPS-1930)
Adds Archera Block and Actions
Merging my forked branch into the rg/archera branch to get my changes in one place and wrap up testing on codespaces. I was not able to establish a connection locally but could on codespaces hence this workaround. Appreciate the patience here!
- Screenshots
- Loom video

Adds Archera Block

---

packages/blocks/archera/src/auth.ts

Add Archera connection instructions

---

packages/react-ui/public/locales/en/translation.json
packages/react-ui/src/app/features/builder/test-step/index.tsx
packages/server/api/src/app/flags/dev-flags.service.ts
packages/ui-components/src/components/json-editor/json-editor.tsx
packages/ui-components/src/components/json-viewer/header-buttons.tsx
packages/ui-components/src/components/json-viewer/json-content.tsx
packages/ui-components/src/components/json-viewer/json-viewer.tsx

Fixes OPS-1947.
Todo: 
Demo
https://www.loom.com/share/0913fea53e3749748283af5503bdd55f

Update fonts&margins and reduce layout shift when toggling sample data viewer/editor mode

---

packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts
packages/server/api/src/app/app-connection/app-connection.controller.ts

Remove USE_CONNECTIONS_PROVIDER reference from BE

---

.devcontainer/Dockerfile
Dockerfile

Update openops-mcp commit hash

---

packages/react-ui/src/app/features/flows/components/import-flow-dialog/import-flow-dialog-content.tsx
packages/react-ui/src/app/features/flows/components/import-flow-dialog/import-flow-dialog.tsx
packages/react-ui/src/app/features/templates/components/connections-picker/connections-picker.tsx
packages/react-ui/src/app/features/templates/components/select-flow-template-dialog.tsx
packages/shared/src/lib/flows/flow-operations.ts

Fix import after connection flag cleanup

---

packages/react-ui/src/app/common/guards/allow-logged-in-user-only-guard.tsx
packages/react-ui/src/app/features/builder/step-settings/block-settings/connection-select.tsx
packages/react-ui/src/app/features/connections/components/connection-table.tsx
packages/react-ui/src/app/features/connections/components/create-edit-connection-dialog-content.tsx
packages/react-ui/src/app/features/connections/components/create-edit-connection-dialog.tsx
packages/react-ui/src/app/features/connections/components/delete-connection-dialog.tsx
packages/react-ui/src/app/features/connections/components/edit-connection-dialog.tsx
packages/react-ui/src/app/features/connections/components/new-connection-type-dialog.tsx
packages/react-ui/src/app/features/connections/components/oauth2-connection-settings.tsx
packages/react-ui/src/app/features/connections/lib/connections-utils.ts
packages/react-ui/src/app/features/flows/components/import-flow-dialog/import-flow-dialog-content.tsx
packages/react-ui/src/app/features/flows/components/import-flow-dialog/import-flow-dialog.tsx
packages/react-ui/src/app/features/templates/components/connections-picker/connections-picker.tsx
packages/react-ui/src/app/features/templates/components/select-flow-template-dialog.tsx
packages/server/api/src/app/app-connection/connection-providers-resolver.ts
packages/server/api/src/app/flows/flow-version/flow-version.service.ts
packages/server/api/src/app/flows/flow/flow.service.ts
packages/server/api/test/unit/app-connection/connection-providers-resolver.test.ts
packages/server/shared/src/lib/system/system.ts
packages/shared/src/lib/app-connection/dto/upsert-app-connection-request.ts
packages/shared/src/lib/flows/flow-helper.ts
packages/shared/src/lib/flows/flow-operations.ts
packages/shared/test/flow/flow-helper.test.ts

Remove blockname from connections in FE

---

packages/server/api/src/app/database/migrations/1750161024797-RemoveBlockNameFromConnectionsTable.ts
packages/server/api/src/app/database/postgres-connection.ts

Remove blockName from connections table

---

packages/server/api/src/app/ai/chat/ai-chat.service.ts
packages/server/api/test/unit/ai/ai-chat.service.test.ts

Remove summarizeMessages callback from ai cache service

---

packages/server/shared/src/lib/system/system.ts

Increase sample data default size limit

---

packages/react-ui/src/app/features/builder/block-properties/auto-properties-form.tsx

Make markdown properties multi-line

---

packages/blocks/cloudzero/src/index.ts

Add documentation link to custom api action in cloudZero

---

packages/react-ui/src/app/features/builder/step-settings/branch-settings/index.tsx

Add new reference every time on new empty condition

---

packages/react-ui/src/app/features/builder/run-details/flow-step-details-card-item.tsx

Fixes OPS-2008.
https://www.loom.com/share/f6d0262628df45b6a114a5e77356aaf5?sid=2250fcd7-c56a-443e-a709-d3483207ca98

Centralize workflow view logic in run details click handler

---

ai-prompts/mcp-aws-cost-unavailable.txt
packages/server/api/src/app/ai/chat/ai-mcp-chat.controller.ts
packages/server/api/src/app/ai/chat/prompts.service.ts
packages/server/api/src/app/ai/mcp/mcp-tools.ts
packages/server/api/test/unit/ai/ai-mcp-chat.controller.test.ts

Include hint in chatbot response that AWS cost MCP needs to be configured

---

ai-prompts/mcp-aws-cost-unavailable.txt

Adjust system prompt to match only questions relevant to AWS cost

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

Change version of node in dev-container

---

.github/workflows/ci.yml

Fixes CI-60.
Thanks @cezudas .

Fix branch sanitization for manifest creation

---

deploy/docker-compose/docker-compose.yml
docker-compose.yml

Bump tables version to latest release on public ECR

---

THIRD_PARTY_LICENSES.txt
package-lock.json
package.json
packages/openops/src/lib/ai/providers/anthropic.ts

Add support for new Anthropic models

---

packages/server/api/src/app/database/migrations/1751281438388-AddInputToTriggerEventTable.ts
packages/server/api/src/app/database/migrations/1751282188913-AddInputToTriggerEventTable.ts
packages/server/api/src/app/database/postgres-connection.ts
packages/server/api/src/app/flows/trigger-events/trigger-event.entity.ts
packages/server/api/src/app/flows/trigger-events/trigger-event.service.ts
packages/shared/src/lib/flows/trigger-events/trigger-event.ts

Add input column to trigger_event table and update logic

---

.cursor/rules/coding-guidelines.mdc

Add cursor rules

---

packages/shared/src/lib/flows/triggers/trigger.ts

Fixes OPS-2072.
https://www.loom.com/share/3524907f3a6448c4bf5e0e0caab21041?sid=604729ac-98ed-468c-b815-bac8929eadd7

Update `UpdateTriggerRequest` to include optional `id` property

---

.github/workflows/release.yml

Trigger deployment when creating a release

---

packages/server/worker/src/lib/executors/flow-job-executor.ts

Use correct jobStatus when there is an internal error

---

packages/engine/src/lib/handler/flow-executor.ts
packages/engine/src/lib/services/progress.service.ts
packages/engine/test/services/progress.service.test.ts
packages/server/api/src/app/workers/engine-controller.ts

Fixes OPS-2109
Add a retry with backoff to the call

Fix engine progress calls

---

packages/engine/src/lib/handler/flow-executor.ts
packages/engine/src/lib/services/progress.service.ts
packages/engine/test/services/progress.service.test.ts

Fix progress issue

---

packages/cli/src/lib/utils/block-templates.ts

Create test directory before writing block test file

---

packages/react-ui/src/app/features/builder/step-settings/block-settings/connection-select.tsx

Prevent reconnect popup from losing pending form changes on tab refocus

---

packages/server/api/src/app/block-variable/block-variable-module.ts

Add limits to variable resolution endpoint

---

packages/react-ui/src/app/features/builder/test-step/test-action-section.tsx

Fixes OPS-2136.
https://www.loom.com/share/8940ab3e77924c0db91c5b06f96fb471?sid=65f81380-be9a-40e9-9db1-e268350c40f5

Fix step test input caching 

---

packages/react-ui/src/app/features/builder/run-details/index.tsx
packages/react-ui/src/app/features/flow-runs/lib/flow-run-utils.ts
packages/react-ui/src/app/features/flow-runs/lib/tests/flow-run-utils.test.ts

Fixes OPS-2146
https://www.loom.com/share/26acaa024bb149d5809dee47ce71dec8?sid=b0f16c5c-668d-48af-8eca-a2382e2f920f

Fix loop output

---

packages/server/api/src/app/database/migrations/1752487641303-AddSuccessToFlowStepTestOutputTable.ts
packages/server/api/src/app/database/postgres-connection.ts
packages/server/api/src/app/flows/flow/flow-version.controller.ts
packages/server/api/src/app/flows/step-run/step-run-service.ts
packages/server/api/src/app/flows/step-test-output/flow-step-test-output-entity.ts
packages/server/api/src/app/flows/step-test-output/flow-step-test-output.service.ts
packages/server/api/src/app/flows/trigger-events/trigger-event.service.ts
packages/server/api/test/integration/ce/flows/flow-step-test-output.test.ts
packages/server/api/test/integration/ce/flows/flow-version.test.ts
packages/shared/src/lib/flows/flow-step-test-output.ts

Add `success` field to `FlowStepTestOutput` and related logic

---

packages/server/api/src/app/telemetry/logzio-collector.ts
packages/server/api/src/app/telemetry/utils/push-timeseries-with-retry.ts
packages/server/api/test/unit/push-timeseries-with-retry.test.ts

Add retry logic for Logz.io metrics push with backoff

---

packages/blocks/ternary/src/lib/actions/get-budgets.ts
packages/blocks/ternary/src/lib/actions/get-data-integrations.ts
packages/blocks/ternary/src/lib/common/index.ts
packages/blocks/ternary/test/common/index.test.ts
packages/blocks/ternary/test/index.test.ts

Part of OPS-2138.
- Also adding some unit tests

Allow multiple HttpMethod in sendTernaryRequest

---

packages/blocks/finout/src/index.ts
packages/blocks/finout/src/lib/actions/add-virtual-tag-filter-value-action.ts
packages/blocks/finout/src/lib/actions/get-view-data-action.ts
packages/blocks/finout/src/lib/actions/get-virtual-tags-action.ts
packages/blocks/finout/src/lib/auth.ts
packages/blocks/finout/src/lib/common/make-request.ts
packages/blocks/finout/src/lib/common/views.ts
packages/blocks/finout/src/lib/common/virtual-tags.ts

Add additional FinOut actions

---

THIRD_PARTY_LICENSES.txt
package-lock.json
package.json
packages/server/shared/src/lib/logger/init-logzio.ts

Update logz.io package and disable opentelemetry

---

packages/react-ui/src/app/features/ai/assistant-ui/assistant-ui-chat.tsx
packages/ui-components/src/components/assistant-ui/assistant-ui-chat-container.tsx
packages/ui-components/src/components/assistant-ui/thread/thread.tsx

Add AI model selector to assistant ui

---

packages/blocks/zendesk/src/index.ts

Fixes OPS-2221.
- Screenshots
- Loom video

Modify 'Organisation' example label in zendesk connection creation form

---

packages/blocks/framework/src/lib/validators/validators.ts
packages/blocks/zendesk/src/index.ts
packages/engine/test/services/variable-service.test.ts

Fix number property default validation

---

packages/react-ui/src/app/features/ai/assistant-ui/assistant-ui-chat.tsx
packages/server/api/src/app/flags/dev-flags.service.ts

Fixes OPS-2205.
https://www.loom.com/share/a98dbe4ec2894d61b986e8fae8dff5a7?sid=1c31121a-05cc-4c85-834b-79f14c1ebd42

Add `New chat` handler to assistant UI chat 

---

packages/blocks/slack/src/lib/actions/request-action-message.ts
packages/blocks/slack/src/lib/common/wait-for-interaction.ts
packages/blocks/slack/test/request-action-message.test.ts

Fix slack interactions returning Unexpected token issue

---

ai-prompts/code.txt
packages/server/api/src/app/ai/chat/context-enrichment.service.ts
packages/shared/src/lib/ai/chat/code-output-structure.ts

Improve code generation prompt / context

---

packages/ui-components/src/components/assistant-ui/markdown-text/markdown-text.tsx

Fixes OPS-2262.
https://www.loom.com/share/422f74c47c6a4f95a9e4af5c01c97d19

Fix memoization bug causing stale status in Code component

---

packages/server/api/src/app/ai/chat/ai-chat.service.ts
packages/server/api/src/app/ai/chat/ai-mcp-chat.controller.ts
packages/server/api/test/unit/ai/ai-mcp-chat.controller.test.ts
packages/server/shared/src/lib/cache/memory-wrapper.ts
packages/server/shared/src/lib/cache/redis-wrapper.ts
packages/shared/src/lib/ai/chat/index.ts

Fixes OPS-2171.
Tested locally and it works
- Screenshots
- Loom video

Add an endpoint to get available AI chats

---

packages/ui-components/src/stories/assistant-ui/tool-fallback.stories.tsx

Disable Chromatic flaky visual test

---

packages/ui-components/src/components/flow-template/flow-template-filter-sidebar.tsx
packages/ui-components/src/stories/flow-template/flow-sidebar.stories.tsx

Fix chevron not pointing down when selecting category

---

packages/blocks/cloudfix/src/index.ts
packages/blocks/cloudfix/src/lib/common/make-request.ts

Fix CloudFix custom api auth

---

.github/workflows/sync-internal.yml

Fix sync workflow name

---

.github/workflows/sync-internal.yml

Fix sync trigger again

---

packages/blocks/archera/src/auth.ts
packages/blocks/archera/src/index.ts
packages/blocks/vegacloud/src/lib/auth.ts

Upload transparent icons for Archera and Vega

---

packages/react-ui/src/app/features/ai/assistant-ui/assistant-ui-chat.tsx
packages/react-ui/src/app/features/ai/lib/assistant-ui-chat-hook.ts

Fixes OPS-2324
https://www.loom.com/share/7d6db7f5216b47a1bf5b0afb90d85467?sid=a93f240e-7b42-4964-b950-5e8c37cf343f

Assistant UI hook fixes for retrieve conversation & New chat

---

packages/react-ui/src/app/features/builder/block-properties/builder-json-wrapper.tsx

Fixes OPS-2334.
https://www.loom.com/share/bb38a63662b5489aaca31f7dbaa7614e?sid=bf7bd87b-2351-4937-9463-95ce3b13a3c6
On UX

Fix datapicker insertion in json field

---

packages/react-ui/src/app/features/builder/block-properties/text-input-with-mentions/text-input-utils.ts

Fixes OPS-2217.
- Screenshots
- Loom video

Display array indices in input as 1-based for consistency with data selector

---

packages/react-ui/public/locales/en/translation.json
packages/ui-components/src/components/index.ts
packages/ui-components/src/components/run-workflow-manually-success-toast/run-workflow-manually-success-toast.tsx
packages/ui-components/src/stories/flows/run-workflow-manually-success-toast.stories.tsx

Fixes OPS-2291.
https://67d165c65ae89f986943666d-xuetwskbeb.chromatic.com/?path=/docs/components-flows-runworkflowmanuallysuccesstoastcontent--docs

Add `RunWorkflowManuallySuccessToast` component and stories

---

THIRD_PARTY_LICENSES.txt
package-lock.json
package.json
packages/openops/src/lib/ai/providers/openai.ts

Fixes OPS-2341.
- Screenshots
- Loom video

Add GPT-5 Models including mini and nano

---

packages/ui-components/src/components/assistant-ui/thread/thread.tsx

Remove assistant ui message branch picker

---

packages/shared/src/lib/flows/flow.ts

Part of OPS-2338
Needed for GET V2 flows

Add flow summary type

---

packages/ui-components/src/components/custom/markdown-components.tsx
packages/ui-components/src/tailwind.css

Fixes OPS-1343.
- Screenshots
- Loom video

Improve ordered list alignment for multi-digit numbers

---

packages/ui-components/src/components/assistant-ui/markdown-text/markdown-text.tsx
packages/ui-components/src/components/assistant-ui/thread/thread.tsx

Fixes OPS-2354
https://www.loom.com/share/a0464961fb434eb6ae05ae763a3baebc

Fix LLM loading indicator

---

packages/react-ui/src/app/features/ai/lib/assistant-ui-chat-hook.ts

Disable open refetch on window focus

---

packages/react-ui/src/app/features/ai/lib/assistant-ui-chat-hook.ts
packages/ui-kit/src/tools/create-frontend-tools.tsx

Fix frontend tool calls after assistant ui bug with AI SDK v5

---

packages/react-ui/src/app/features/builder/block-properties/array-property.tsx

Allow dynamic values inside complex array

---

packages/ui-components/src/components/assistant-ui/tool-fallback/base-tool-wrapper.tsx
packages/ui-components/src/stories/assistant-ui/tool-fallback.stories.tsx

Improve tools display

---

packages/blocks/end-flow/src/index.ts
packages/blocks/end-flow/src/lib/actions/end-workflow.ts

Fixes OPS-2389.
- Screenshots
- Loom video

Rename 'End workflow' action with 'Stop Execution"

---

packages/engine/src/lib/helper/trigger-helper.ts
packages/server/api/src/app/flows/trigger/hooks/enable-trigger-hook.ts

Fix scheduling triggers not respecting the defined time

---

packages/server/api/src/app/flows/flow/flow.service.ts
packages/server/api/src/app/helper/pagination/build-paginator.ts
packages/server/api/src/app/helper/pagination/pagination-utils.ts
packages/server/api/src/app/helper/pagination/paginator.ts
packages/server/api/test/helpers/pagination-utils.test.ts
packages/server/api/test/integration/helper/pagination/paginator.integration.test.ts

Fixes OPS-1227.
Demo of the cursor calculation issues (before): https://www.loom.com/share/b49df91ca94d4d7b957675d58b2d6c92

Fix paginator cursor calculation issues for forward and backward navigation 

---

packages/react-ui/src/app/features/templates/components/select-flow-template-dialog.tsx
packages/react-ui/src/app/features/templates/lib/templates-hooks.ts
packages/server/api/src/app/flow-template/cloud-template.controller.ts
packages/ui-components/src/components/flow-template/flow-template-filter-sidebar.tsx
packages/ui-components/src/components/flow-template/flow-template-list.tsx

Fixes OPS-2464.
Deployed to test. design approved by Olga

Add filters to the sample templates dialog

---

packages/shared/src/lib/flows/triggers/trigger.ts

Fix trigger description

---

packages/server/api/src/app/project/project-service.ts
packages/server/api/test/integration/cloud/project/project.service.test.ts

Get projectIds from organization ID

---

.github/workflows/sync-internal.yml

Resolves CI-83. No need to wait for the CI build.

Trigger sync after each push to main

---

packages/react-ui/src/app/features/builder/data-selector/data-selector-utils.ts
packages/ui-components/src/components/code-editor/code-editor.tsx

This reverts commit 02830dc3bcf9e3db67e8f8e91196aa6b0a817b9d.
Part of OPS-2438.
We need another solution as search doesn't work for that one

Revert "Improve data picker performance (#1179)"

---

packages/server/api/src/app/database/migrations/1756377588949-RenameIsWorkflowToIsInternal.ts
packages/server/api/src/app/database/postgres-connection.ts
packages/server/api/src/app/flows/flow/flow.entity.ts
packages/server/api/src/app/flows/flow/flow.service.ts
packages/server/api/src/app/helper/error-handler.ts
packages/server/api/test/helpers/mocks/index.ts
packages/shared/src/lib/flows/flow.ts

Rename isWorkflow to isInternal and Dont allow flow to be published if isInternal is set to false

---

packages/ui-components/src/components/assistant-ui/tool-fallback/tests/tool-json-parser.test.ts
packages/ui-components/src/components/assistant-ui/tool-fallback/tool-fallback.tsx
packages/ui-components/src/components/assistant-ui/tool-fallback/tool-json-parser.ts

Add content-based error detection for MCP tool responses

---

packages/react-ui/src/app/features/templates/components/select-flow-template-dialog-content.tsx
packages/react-ui/src/app/features/templates/components/select-flow-template-dialog.tsx
packages/react-ui/src/app/features/templates/lib/private-templates-hook.ts
packages/ui-components/src/components/flow-template/flow-template-gallery-private-tab.tsx
packages/ui-components/src/components/flow-template/flow-template-gallery.tsx
packages/ui-components/src/components/flow-template/no-private-templates-catalog.tsx

Refactor templates dialog to modularize private tab handling

---

packages/react-ui/src/app/features/builder/hooks/use-flow-updates.ts
packages/react-ui/src/app/features/builder/index.tsx
packages/shared/src/lib/websocket/index.ts

Builder socket updates

---

packages/shared/src/lib/flows/actions/action.ts
packages/shared/src/lib/flows/triggers/trigger.ts

Fix action name / trigger name descriptions

---

packages/shared/src/lib/flows/triggers/trigger.ts

Use GET for webhooks by default

---

packages/server/api/src/app/flows/flow/flow.controller.ts
packages/server/api/src/app/flows/flow/flow.service.ts

Rename createFromTemplate to createFromTrigger for reusability

---

packages/server/api/src/app/flows/flow/flow.service.ts

Allow adding folder id and isInternal when creating from trigger

---

packages/react-ui/src/app/features/builder/run-details/index.tsx

Add status icon with explanation to Run Details sidebar (#1235)

---

tools/link-packages.sh

Fix linking script for multi-os compatibility

---

packages/react-ui/src/app/features/folders/component/folder-breadcrumbs-manager.tsx
packages/react-ui/src/app/features/folders/lib/flows-table-filters.ts
packages/react-ui/src/app/features/folders/lib/selected-folder-hook.ts
packages/react-ui/src/app/routes/flows/index.tsx

Part of OPS-2423.
We need it to reuse them on private templates page

Modularize flows table page

---

packages/react-ui/src/app/features/templates/components/select-flow-template-dialog-content.tsx
packages/react-ui/src/app/features/templates/components/select-flow-template-dialog.tsx

Part of OPS-2426.
Need it on the parent level to control the requests

Refactor `SelectFlowTemplateDialog` to lift `activeTab` state management to parent component

---

packages/ui-components/src/components/assistant-ui/tool-fallback/base-tool-wrapper.tsx
packages/ui-components/src/components/assistant-ui/tool-fallback/tool-fallback.tsx
packages/ui-components/src/components/assistant-ui/tool-status.ts

Display cancelled tool results as failures

---

packages/shared/src/lib/ai/tool-approval/constants.ts
packages/shared/src/lib/ai/tool-approval/index.ts
packages/shared/src/lib/ai/tool-approval/types.ts

Add shared tool approval timeout constant

---

packages/ui-components/src/ui/data-table.tsx

Keep datatable filter UI state in sync with URL search params

---

packages/react-ui/src/app/features/builder/builder-header/builder-header.tsx
packages/react-ui/src/app/routes/flows/id/index.tsx
packages/react-ui/src/app/routes/runs/id/index.tsx

Modularize `BuilderHeader` to accept `PublishButton` and `DetailsPanel` as props

---

packages/react-ui/src/app/features/ai/assistant/ai-chat-resizable-panel.tsx
packages/react-ui/src/app/features/navigation/layout/global-layout.tsx

Fix typo in layout

---

packages/react-ui/src/app/features/builder/builder-header/builder-header.tsx

Update `BuilderHeader` to accept `className` prop for custom styling

---

packages/server/api/src/app/flows/flow-run/flow-run-service.ts
packages/server/api/test/integration/ce/flows/flow-run/list-flow-runs.test.ts

Dont include isInternal=true flows in flow run page

---

packages/blocks/cloudhealth/src/lib/common/call-rest-api.ts
packages/blocks/cloudhealth/src/lib/common/get-asset-fields.ts
packages/blocks/cloudhealth/src/lib/common/get-asset-types.ts
packages/blocks/cloudhealth/src/lib/common/get-aws-accounts.ts
packages/blocks/cloudhealth/src/lib/common/search-assets.ts

Paginate CH Get AWS accounts response

---

packages/server/api/src/app/flows/folder/flow-filter-util.ts
packages/server/api/src/app/flows/folder/folder-flows.ts
packages/server/api/src/app/flows/folder/tests/flow-filter.utils.test.ts
packages/server/api/src/app/flows/folder/uncategorized-flows.ts

Add helper function for getting workflow folders

---

packages/engine/src/lib/handler/block-executor.ts
packages/engine/src/lib/handler/code-executor.ts
packages/server/shared/src/lib/promise-handler.ts

Log the execution of Code and Block steps

---

packages/engine/src/lib/handler/block-executor.ts
packages/engine/src/lib/handler/code-executor.ts

Add duration and status to the step execution log

---

packages/react-ui/src/app/features/builder/step-settings/index.tsx
packages/react-ui/src/app/features/builder/test-step/index.tsx
packages/ui-components/src/components/builder-sidebar/sidebar-header.tsx

Fixes OPS-2644 and OPS-2637
Deployed to UX

Pin cofigure/test tabs in new step settings UI

---

packages/server/api/src/app/ai/chat/chat-request-router.ts
packages/server/api/src/app/ai/chat/code-generation-handler.ts
packages/server/api/src/app/ai/chat/code.service.ts
packages/server/api/src/app/ai/chat/llm-stream-handler.ts
packages/server/api/src/app/ai/chat/user-message-handler.ts
packages/server/api/src/app/ai/mcp/llm-query-router.ts
packages/server/api/src/app/ai/mcp/tools-context-builder.ts
packages/server/api/src/app/telemetry/event-models/ai.ts
packages/server/api/test/unit/ai/chat-request-router.test.ts
packages/server/api/test/unit/ai/user-message-handler.test.ts
packages/server/api/test/unit/mcp/llm-query-router.test.ts
packages/server/api/test/unit/mcp/tools-context.test.ts

Cancel the back-end stream when the user clicks on chat cancel button

---

packages/server/api/src/app/ai/mcp/cost-tools.ts
packages/server/api/src/app/ai/mcp/docs-tools.ts
packages/server/api/src/app/ai/mcp/load-tools-guard.ts
packages/server/api/src/app/ai/mcp/openops-tools.ts
packages/server/api/src/app/ai/mcp/superset-tools.ts
packages/server/api/src/app/ai/mcp/tables-tools.ts
packages/server/api/src/app/ai/mcp/tools-initializer.ts
packages/server/api/src/app/ai/mcp/types.ts

Move safeGetTools method to load-tools-guard file

---

packages/react-ui/src/app/features/builder/test-step/test-trigger-section.tsx

Handle `errorMessage` in visibility check for test trigger section

---

packages/server/api/src/app/ai/chat/user-message-handler.ts

Persist successful steps result to message history when stream is cancelled via abort signal

---

packages/react-ui/src/app/features/flows/components/flow-status-toggle.tsx

Improve layout of workflow status toggle tooltip

---

packages/react-ui/src/app/features/ai/lib/assistant-ui-chat-hook.ts
packages/react-ui/src/app/features/builder/builder-state-provider.tsx

Sync LLM conversation additional context with builder state

---

packages/blocks/imap/src/lib/common/build-client.ts
packages/server/shared/src/lib/job/index.ts
packages/server/shared/src/lib/system/system.ts

Update imap timeouts

---

packages/blocks/imap/src/lib/common/fetch-emails.ts
packages/blocks/imap/src/lib/common/imap-auth.ts
packages/blocks/imap/src/lib/common/mailbox.ts
packages/blocks/imap/test/mailbox.test.ts

Update IMAP error handling 

---

packages/react-ui/src/app/app.tsx
packages/react-ui/src/app/lib/authentication-session.ts
packages/react-ui/src/app/lib/navigation-constants.ts
packages/react-ui/src/app/lib/navigation-events.ts
packages/react-ui/src/app/lib/navigation-util.ts

Redirect users to correct page across tabs after session expiry

---

packages/react-ui/src/app/features/builder/block-properties/auto-form-field-wrapper.tsx
packages/react-ui/src/app/features/builder/builder-types.ts
packages/react-ui/src/app/features/builder/step-settings/block-settings/connection-select.tsx
packages/react-ui/src/app/features/builder/step-settings/block-settings/index.tsx

Update connections select to work outside step settings

---

packages/server/shared/src/lib/system/system.ts

Update MAX_LLM_CALLS_WITHOUT_INTERACTION to 100

---

packages/react-ui/src/app/features/builder/index.tsx

Fixes OPS-2688.
https://www.loom.com/share/53437315ed4f41d8ba23fce1dd44e047

Prevent step settings remount when draft version is created

---

packages/ui-components/src/components/assistant-ui/tool-fallback/base-tool-wrapper.tsx

Fixes OPS-2743.
See the Linear ticket comment section for screenshots.
TODO:

Fix space between succesive tool calls

---

packages/blocks/ai/src/lib/actions/askAi.ts
packages/blocks/ai/test/askAi-action.test.ts

Add model selector to "Ask AI" action

---

packages/server/api/src/app/ai/mcp/llm-query-router.ts

Add safeguard for getting table names in query router

---

.github/dependabot.yml

Update Dependabot schedule interval to monthly

---

packages/react-ui/src/app/features/builder/step-settings/index.tsx
packages/react-ui/src/app/features/builder/test-step/index.tsx

Prevent async fields reload in step-settings when tabs state changed

---

packages/blocks/microsoft-outlook/src/lib/triggers/new-email.ts

Get full body for email

---

packages/server/api/src/app/ai/chat/context-cache.helper.ts
packages/server/api/src/app/ai/chat/llm-stream-handler.ts
packages/server/api/test/unit/ai/context-cache.helper.test.ts

Fix context cache

---

packages/blocks/aws/test/add-tags-action.test.ts
packages/openops/src/lib/aws/tags/tag-resources.ts
packages/openops/test/aws/tags/tag-resources.test.ts

Throw if failed to tag some AWS resources
